.TH "blade-config.php" 3 "Mardi 23 Juillet 2024" "Version 1.1.1" "Sabo final" \" -*- nroff -*-
.ad l
.nh
.SH NAME
blade-config.php
.SH SYNOPSIS
.br
.PP
.SS "Fonctions"

.in +1c
.ti -1c
.RI "\fBbladeJsRoutes\fP (array $routes,?string $funcNameReplace=null,?string $customIdReplace=null)"
.br
.RI "Fichier de configuration blade\&. "
.in -1c
.SH "Documentation des fonctions"
.PP 
.SS "bladeJsRoutes (array $routes, ?string $funcNameReplace = \fCnull\fP, ?string $customIdReplace = \fCnull\fP)"

.PP
Fichier de configuration blade\&. Fourni les routes à javascript 
.PP
\fBParamètres\fP
.RS 4
\fI$routes\fP liste des routes (tableau du format ([method, name, [params → \&.\&.\&.]]) 
.br
\fI$funcNameReplace\fP nom de remplacement pour la fonction js 
.br
\fI$customIdReplace\fP nom de remplacement pour l'id du script js 
.RE
.PP
\fBRenvoie\fP
.RS 4
string balise javascript contenant la fonction getRouteList contenant les routes nommées 
.RE
.PP

.PP
Définition à la ligne \fB18\fP du fichier \fBblade\-config\&.php\fP\&.
.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Sabo final à partir du code source\&.
