.TH "Répertoire de référence de session" 3 "Mardi 23 Juillet 2024" "Version 1.1.1" "Sabo final" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Répertoire de référence de session
.SH SYNOPSIS
.br
.PP
.SS "Fichiers"

.in +1c
.ti -1c
.RI "fichier \fBFrameworkSession\&.php\fP"
.br
.ti -1c
.RI "fichier \fBSessionStorage\&.php\fP"
.br
.ti -1c
.RI "fichier \fBSessionStorageKeymap\&.php\fP"
.br
.in -1c
