.TH "Répertoire de référence de views" 3 "Mardi 23 Juillet 2024" "Version 1.1.1" "Sabo final" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Répertoire de référence de views
.SH SYNOPSIS
.br
.PP
.SS "Répertoires"

.in +1c
.ti -1c
.RI "répertoire \fBmaintenance\fP"
.br
.in -1c
.SS "Fichiers"

.in +1c
.ti -1c
.RI "fichier \fBsabo\&.blade\&.php\fP"
.br
.in -1c
