.TH "Répertoire de référence de src" 3 "Mardi 23 Juillet 2024" "Version 1.1.1" "Sabo final" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Répertoire de référence de src
.SH SYNOPSIS
.br
.PP
.SS "Répertoires"

.in +1c
.ti -1c
.RI "répertoire \fBconfigs\fP"
.br
.ti -1c
.RI "répertoire \fBcontrollers\fP"
.br
.ti -1c
.RI "répertoire \fBmodels\fP"
.br
.ti -1c
.RI "répertoire \fBroutes\fP"
.br
.ti -1c
.RI "répertoire \fBstorage\fP"
.br
.ti -1c
.RI "répertoire \fBtreatment\fP"
.br
.ti -1c
.RI "répertoire \fBviews\fP"
.br
.in -1c
