.TH "Répertoire de référence de default" 3 "Mardi 23 Juillet 2024" "Version 1.1.1" "Sabo final" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Répertoire de référence de default
.SH SYNOPSIS
.br
.PP
.SS "Répertoires"

.in +1c
.ti -1c
.RI "répertoire \fBattributes\fP"
.br
.ti -1c
.RI "répertoire \fBconditions\fP"
.br
.ti -1c
.RI "répertoire \fBcustom\-datatypes\fP"
.br
.ti -1c
.RI "répertoire \fBformatters\fP"
.br
.ti -1c
.RI "répertoire \fBprovider\fP"
.br
.ti -1c
.RI "répertoire \fBquery\-builder\fP"
.br
.ti -1c
.RI "répertoire \fBsystem\fP"
.br
.in -1c
