.TH "CustomController" 3 "Mardi 23 Juillet 2024" "Version 1.1.1" "Sabo final" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CustomController \- Controller customisé de l'application\&.  

.SH SYNOPSIS
.br
.PP
.PP
Est dérivée de \fBController\fP\&.
.SS "Membres hérités additionnels"


Fonctions membres publiques hérités de \fBController\fP
.in +1c
.ti -1c
.RI "\fB__construct\fP ()"
.br
.in -1c
.SH "Description détaillée"
.PP 
Controller customisé de l'application\&. 
.PP
Définition à la ligne \fB10\fP du fichier \fBCustomController\&.php\fP\&.

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Sabo final à partir du code source\&.
