.TH "functions.php" 3 "Mardi 23 Juillet 2024" "Version 1.1.1" "Sabo final" \" -*- nroff -*-
.ad l
.nh
.SH NAME
functions.php
.SH SYNOPSIS
.br
.PP
.SS "Fonctions"

.in +1c
.ti -1c
.RI "\fBdebug\fP (mixed \&.\&.\&. $toDebug)"
.br
.RI "Débug les variables fournies\&. "
.ti -1c
.RI "\fBdebugDie\fP (mixed \&.\&.\&. $toDebug)"
.br
.RI "Débug les variables fournies et quitte le programme\&. "
.ti -1c
.RI "\fBroute\fP (string $requestMethod, string $routeName, array $replaces=[])"
.br
.RI "Recherche une route pour la fournir\&. "
.ti -1c
.RI "\fBgenerateCsrf\fP ()"
.br
.RI "Génère un token csrf\&. "
.ti -1c
.RI "\fBcheckCsrf\fP (string $token)"
.br
.RI "Vérifie que le token soit valide et le supprime si valide\&. "
.in -1c
.SH "Documentation des fonctions"
.PP 
.SS "checkCsrf (string $token)"

.PP
Vérifie que le token soit valide et le supprime si valide\&. 
.PP
\fBParamètres\fP
.RS 4
\fI$token\fP 
.RE
.PP
\fBRenvoie\fP
.RS 4
bool si le token est valide 
.RE
.PP

.PP
Définition à la ligne \fB91\fP du fichier \fBfunctions\&.php\fP\&.
.SS "debug (mixed \&.\&.\&. $toDebug)"

.PP
Débug les variables fournies\&. 
.PP
\fBParamètres\fP
.RS 4
\fImixed\fP \&.\&.\&.$toDebug variables à débugger 
.RE
.PP
\fBRenvoie\fP
.RS 4
void 
.RE
.PP

.PP
Définition à la ligne \fB22\fP du fichier \fBfunctions\&.php\fP\&.
.SS "debugDie (mixed \&.\&.\&. $toDebug)"

.PP
Débug les variables fournies et quitte le programme\&. 
.PP
\fBParamètres\fP
.RS 4
\fImixed\fP \&.\&.\&.$toDebug variables à débugger 
.RE
.PP

.PP
Définition à la ligne \fB30\fP du fichier \fBfunctions\&.php\fP\&.
.SS "generateCsrf ()"

.PP
Génère un token csrf\&. 
.PP
\fBRenvoie\fP
.RS 4
CsrfManager le gestion de token 
.RE
.PP

.PP
Définition à la ligne \fB71\fP du fichier \fBfunctions\&.php\fP\&.
.SS "route (string $requestMethod, string $routeName, array $replaces = \fC[]\fP)"

.PP
Recherche une route pour la fournir\&. 
.PP
\fBParamètres\fP
.RS 4
\fI$requestMethod\fP méthode de requête 
.br
\fI$routeName\fP nom de la route 
.br
\fIarray<string,string>\fP $replaces éléments de remplacements dans le lien 
.RE
.PP
\fBRenvoie\fP
.RS 4
string|null le lien lié à la route 
.RE
.PP

.PP
Définition à la ligne \fB42\fP du fichier \fBfunctions\&.php\fP\&.
.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Sabo final à partir du code source\&.
