.TH "JsonColumn" 3 "Mardi 23 Juillet 2024" "Version 1.1.1" "Sabo final" \" -*- nroff -*-
.ad l
.nh
.SH NAME
JsonColumn \- Champs de type json\&.  

.SH SYNOPSIS
.br
.PP
.PP
Est dérivée de \fBTableColumn\fP\&.
.SS "Fonctions membres publiques"

.in +1c
.ti -1c
.RI "\fB__construct\fP (string $columnName, bool $\fBisNullable\fP=false, bool $\fBisPrimaryKey\fP=false, bool $\fBisUnique\fP=false, string $defaultValue=self::NO_DEFAULT_VALUE, bool $\fBisForeignKey\fP=false, ?string $referencedModel=null, ?string $referencedAttributeName=null, array $setConditions=[], array $dataFormatters=[], array $datasReformers=[])"
.br
.ti -1c
.RI "\fBgetCreationSql\fP ()"
.br
.ti -1c
.RI "\fBgetColumnType\fP ()"
.br
.in -1c

Fonctions membres publiques hérités de \fBTableColumn\fP
.in +1c
.ti -1c
.RI "\fB__construct\fP (string $columnName, bool $\fBisNullable\fP=false, bool $\fBisPrimaryKey\fP=false, bool $\fBisUnique\fP=false, string $defaultValue=self::NO_DEFAULT_VALUE, bool $\fBisForeignKey\fP=false,?string $referencedModel=null,?string $referencedAttributeName=null, array $setConditions=[], array $dataFormatters=[], array $datasReformers=[])"
.br
.ti -1c
.RI "\fBverifyData\fP (\fBMysqlModel\fP $baseModel, string $attributeName, mixed $data)"
.br
.RI "Vérifie la donnée à affecter\&. "
.ti -1c
.RI "\fBformatData\fP (\fBMysqlModel\fP $baseModel, mixed $originalData)"
.br
.RI "Formate la donnée originale en passant par les formateurs\&. "
.ti -1c
.RI "\fBreformData\fP (\fBMysqlModel\fP $baseModel, mixed $formatedData)"
.br
.RI "Reforme la donnée originale en passant par les reconstructeurs\&. "
.ti -1c
.RI "\fBgetColumnName\fP ()"
.br
.ti -1c
.RI "\fBisPrimaryKey\fP ()"
.br
.ti -1c
.RI "\fBisForeignKey\fP ()"
.br
.ti -1c
.RI "\fBisNullable\fP ()"
.br
.ti -1c
.RI "\fBisUnique\fP ()"
.br
.ti -1c
.RI "\fBgetReferencedModel\fP ()"
.br
.ti -1c
.RI "\fBgetSetConditions\fP ()"
.br
.ti -1c
.RI "\fBgetDefaultValueStr\fP ()"
.br
.ti -1c
.RI "\fBhaveDefaultValue\fP ()"
.br
.ti -1c
.RI "\fBgetDatasFormatters\fP ()"
.br
.ti -1c
.RI "\fBgetDatasReformers\fP ()"
.br
.ti -1c
.RI "\fBgetReferencedAttributeName\fP ()"
.br
.ti -1c
.RI "\fBconvertToValue\fP (mixed $data)"
.br
.RI "Méthode appellé au montage de la propriété portant cet attribut\&. Transforme la donnée récupérée en base de donnée en la donnée finale\&. "
.ti -1c
.RI "\fBconvertFromValue\fP (mixed $data)"
.br
.RI "Méthode appellé à l'insertion ou mise à jour de la propriété portant cet attribut\&. Transforme la donnée de l'attribut en une donnée capable d'être inséré en base de donnée\&. "
.ti -1c
.RI "\fBgetColumnType\fP ()"
.br
.in -1c
.in +1c
.ti -1c
.RI "\fBgetCreationSql\fP ()"
.br
.in -1c
.SS "Membres hérités additionnels"


Attributs protégés hérités de \fBTableColumn\fP
.in +1c
.ti -1c
.RI "const string \fBNO_DEFAULT_VALUE\fP = 'ATTRIBUTE_NO_DEFAULT_VALUE'"
.br
.RI "Chaine représentant si l'attribut n'a pas de valeur par défaut\&. "
.ti -1c
.RI "string \fB$columnName\fP"
.br
.ti -1c
.RI "bool \fB$isPrimaryKey\fP"
.br
.ti -1c
.RI "bool \fB$isForeignKey\fP"
.br
.ti -1c
.RI "bool \fB$isNullable\fP"
.br
.ti -1c
.RI "bool \fB$isUnique\fP"
.br
.ti -1c
.RI "string \fB$defaultValue\fP"
.br
.ti -1c
.RI "string \fB$referencedModel\fP"
.br
.ti -1c
.RI "string \fB$referencedAttributeName\fP"
.br
.ti -1c
.RI "array \fB$setConditions\fP"
.br
.ti -1c
.RI "array \fB$datasFormatters\fP = []"
.br
.ti -1c
.RI "array \fB$datasReformers\fP = []"
.br
.in -1c
.SH "Description détaillée"
.PP 
Champs de type json\&. 


.PP
\fBAuteur\fP
.RS 4
yahaya bathily https://github.com/yahvya 
.RE
.PP

.PP
Définition à la ligne \fB14\fP du fichier \fBJsonColumn\&.php\fP\&.
.SH "Documentation des constructeurs et destructeur"
.PP 
.SS "__construct (string $columnName, bool $isNullable = \fCfalse\fP, bool $isPrimaryKey = \fCfalse\fP, bool $isUnique = \fCfalse\fP, string $defaultValue = \fCself::NO_DEFAULT_VALUE\fP, bool $isForeignKey = \fCfalse\fP, ?string $referencedModel = \fCnull\fP, ?string $referencedAttributeName = \fCnull\fP, array $setConditions = \fC[]\fP, array $dataFormatters = \fC[]\fP, array $datasReformers = \fC[]\fP)"

.PP
\fBParamètres\fP
.RS 4
\fI$columnName\fP Nom de la colonne en base de donnée 
.br
\fI$isNullable\fP si le champ est nullable (mis à false par défaut si clé primaire) 
.br
\fI$isPrimaryKey\fP si le champ est une clé primaire 
.br
\fI$isUnique\fP si le champ est unique 
.br
\fI$defaultValue\fP Valeur par défaut de l'attribut (sous la forme sql) 
.br
\fI$isForeignKey\fP si le champ est une clé étrangère 
.br
\fI$referencedModel\fP Class du modèle référencé par la clé 
.br
\fI$referencedAttributeName\fP Nom de l'attribut référencé 
.br
\fI$setConditions\fP Conditions à vérifier sur la donnée originale avant de l'accepter dans l'attribut 
.br
\fI$dataFormatters\fP Formateur de donnée pour transformer la donnée originale 
.br
\fI$datasReformers\fP Formateur de donnée pour reformer la donnée 
.RE
.PP
\fBAttention\fP
.RS 4
Les conditions sont appelées avant formatage sur la donnée originale 
.PP
Chaque formateur recevra le résultat du précédent 
.PP
L'attribut par défaut doit contenir la chaine exacte qui sera saisie dans la création sql ex : ''default'' '10' \&.\&.\&. 
.RE
.PP

.PP
Réimplémentée à partir de \fBTableColumn\fP\&.
.PP
Définition à la ligne \fB15\fP du fichier \fBJsonColumn\&.php\fP\&.
.SH "Documentation des fonctions membres"
.PP 
.SS "getColumnType ()"

.PP
\fBRenvoie\fP
.RS 4
int Fourni le type de paramètre pdo 
.RE
.PP

.PP
Réimplémentée à partir de \fBTableColumn\fP\&.
.PP
Définition à la ligne \fB41\fP du fichier \fBJsonColumn\&.php\fP\&.
.SS "getCreationSql ()"

.PP
\fBRenvoie\fP
.RS 4
string Fourni le sql de création de l'attribut 
.RE
.PP

.PP
Réimplémentée à partir de \fBSqlAttribute\fP\&.
.PP
Définition à la ligne \fB32\fP du fichier \fBJsonColumn\&.php\fP\&.

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Sabo final à partir du code source\&.
