.TH "MysqlCondition" 3 "Mardi 23 Juillet 2024" "Version 1.1.1" "Sabo final" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MysqlCondition \- Condition mysql\&.  

.SH SYNOPSIS
.br
.PP
.PP
Est dérivée de \fBDatabaseCondition\fP\&.
.SS "Fonctions membres publiques"

.in +1c
.ti -1c
.RI "\fB__construct\fP (mixed $condGetter, \fBMysqlComparator\fP $comparator, mixed $conditionValue)"
.br
.ti -1c
.RI "\fBgetCondGetter\fP ()"
.br
.ti -1c
.RI "\fBgetComparator\fP ()"
.br
.in -1c

Fonctions membres publiques hérités de \fBDatabaseCondition\fP
.in +1c
.ti -1c
.RI "\fB__construct\fP (mixed $condGetter, \fBDatabaseComparator\fP $comparator, mixed $conditionValue)"
.br
.ti -1c
.RI "\fBgetCondGetter\fP ()"
.br
.ti -1c
.RI "\fBgetConditionValue\fP ()"
.br
.ti -1c
.RI "\fBgetComparator\fP ()"
.br
.in -1c
.SS "Membres hérités additionnels"


Attributs protégés hérités de \fBDatabaseCondition\fP
.in +1c
.ti -1c
.RI "mixed \fB$condGetter\fP"
.br
.ti -1c
.RI "mixed \fB$conditionValue\fP"
.br
.ti -1c
.RI "\fBDatabaseComparator\fP \fB$comparator\fP"
.br
.in -1c
.SH "Description détaillée"
.PP 
Condition mysql\&. 


.PP
\fBAuteur\fP
.RS 4
yahaya bathily https://github.com/yahvya 
.RE
.PP

.PP
Définition à la ligne \fB13\fP du fichier \fBMysqlCondition\&.php\fP\&.
.SH "Documentation des constructeurs et destructeur"
.PP 
.SS "__construct (mixed $condGetter, \fBMysqlComparator\fP $comparator, mixed $conditionValue)"

.PP
\fBParamètres\fP
.RS 4
\fI$condGetter\fP Nom de l'attribut ou Fonction mysql 
.br
\fI$comparator\fP Comparateur 
.br
\fI$conditionValue\fP Valeur à vérifier 
.RE
.PP
\fBAttention\fP
.RS 4
En cas de getter sous forme de condition, veuillez ne pas fournir d'alias 
.RE
.PP

.PP
Définition à la ligne \fB20\fP du fichier \fBMysqlCondition\&.php\fP\&.
.SH "Documentation des fonctions membres"
.PP 
.SS "getComparator ()"

.PP
\fBRenvoie\fP
.RS 4
MysqlComparator comparateur 
.RE
.PP

.PP
Réimplémentée à partir de \fBDatabaseCondition\fP\&.
.PP
Définition à la ligne \fB36\fP du fichier \fBMysqlCondition\&.php\fP\&.
.SS "getCondGetter ()"

.PP
\fBRenvoie\fP
.RS 4
MysqlFunction|string le nom de l'attribut ou la fonction 
.RE
.PP

.PP
Réimplémentée à partir de \fBDatabaseCondition\fP\&.
.PP
Définition à la ligne \fB28\fP du fichier \fBMysqlCondition\&.php\fP\&.

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Sabo final à partir du code source\&.
