.TH "FileManager" 3 "Mardi 23 Juillet 2024" "Version 1.1.1" "Sabo final" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FileManager \- Gestionnaire de fichier serveur\&.  

.SH SYNOPSIS
.br
.PP
.PP
Est dérivée de \fBStorable\fP\&.
.PP
Dérivée par \fBFormFileManager\fP\&.
.SS "Fonctions membres publiques"

.in +1c
.ti -1c
.RI "\fB__construct\fP (string $fileAbsolutePath)"
.br
.ti -1c
.RI "\fBfileExists\fP ()"
.br
.ti -1c
.RI "\fBgetExtension\fP (bool $fromFirstOccur=true, string $extensionSeparator='\&.')"
.br
.RI "Recherche l'extension du fichier\&. "
.ti -1c
.RI "\fBgetToDownload\fP (?string $fileName=null)"
.br
.ti -1c
.RI "\fBgetPath\fP ()"
.br
.ti -1c
.RI "\fBstoreIn\fP (string $path, bool $createFoldersIfNotExists=true)"
.br
.RI "Stock le fichier dans le dossier de stockage (en conservant le fichier actuel) "
.ti -1c
.RI "\fBdelete\fP ()"
.br
.RI "Supprime le fichier\&. "
.ti -1c
.RI "\fBgetFromStorage\fP ()"
.br
.in -1c

Fonctions membres publiques hérités de \fBStorable\fP
.in +1c
.ti -1c
.RI "\fBstoreIn\fP (string $path)"
.br
.RI "Stocke l'élément\&. "
.ti -1c
.RI "\fBgetFromStorage\fP ()"
.br
.in -1c
.SS "Attributs protégés"

.in +1c
.ti -1c
.RI "string \fB$fileAbsolutePath\fP"
.br
.in -1c
.SH "Description détaillée"
.PP 
Gestionnaire de fichier serveur\&. 


.PP
\fBAuteur\fP
.RS 4
yahaya bathily 
.RE
.PP

.PP
Définition à la ligne \fB15\fP du fichier \fBFileManager\&.php\fP\&.
.SH "Documentation des constructeurs et destructeur"
.PP 
.SS "__construct (string $fileAbsolutePath)"

.PP
\fBParamètres\fP
.RS 4
\fI$fileAbsolutePath\fP chemin absolue du fichier 
.RE
.PP

.PP
Définition à la ligne \fB24\fP du fichier \fBFileManager\&.php\fP\&.
.SH "Documentation des fonctions membres"
.PP 
.SS "delete ()"

.PP
Supprime le fichier\&. 
.PP
\fBRenvoie\fP
.RS 4
bool si la suppression a réussie 
.RE
.PP

.PP
Réimplémentée dans \fBFormFileManager\fP\&.
.PP
Définition à la ligne \fB91\fP du fichier \fBFileManager\&.php\fP\&.
.SS "fileExists ()"

.PP
\fBRenvoie\fP
.RS 4
bool si le fichier existe 
.RE
.PP

.PP
Définition à la ligne \fB31\fP du fichier \fBFileManager\&.php\fP\&.
.SS "getExtension (bool $fromFirstOccur = \fCtrue\fP, string $extensionSeparator = \fC'\&.'\fP)"

.PP
Recherche l'extension du fichier\&. 
.PP
\fBParamètres\fP
.RS 4
\fI$fromFirstOccur\fP Si true récupère le chemin à partir du premier '\&.' rencontré (ex : file\&.blade\&.php = blade\&.php) sinon le dernier (ex : file\&.blade\&.php = php) 
.br
\fI$extensionSeparator\fP séparateur d'extension '\&.' par défaut 
.RE
.PP
\fBRenvoie\fP
.RS 4
string|null l'extension trouvée ou 
.RE
.PP

.PP
Définition à la ligne \fB41\fP du fichier \fBFileManager\&.php\fP\&.
.SS "getFromStorage ()"

.PP
\fBRenvoie\fP
.RS 4
FileContentManager|null gestionnaire de contenu de fichier si échec de lecture du contenu 
.RE
.PP
\fBAttention\fP
.RS 4
adapté aux fichiers à contenu textuel 
.RE
.PP

.PP
Implémente \fBStorable\fP\&.
.PP
Réimplémentée dans \fBFormFileManager\fP\&.
.PP
Définition à la ligne \fB100\fP du fichier \fBFileManager\&.php\fP\&.
.SS "getPath ()"

.PP
\fBRenvoie\fP
.RS 4
string le chemin du fichier contenu 
.RE
.PP

.PP
Définition à la ligne \fB68\fP du fichier \fBFileManager\&.php\fP\&.
.SS "getToDownload (?string $fileName = \fCnull\fP)"

.PP
\fBParamètres\fP
.RS 4
\fI$fileName\fP nom à donner au fichier téléchargé ou null pour conserver le nom par défaut 
.RE
.PP
\fBRenvoie\fP
.RS 4
DownloadResponse le fichier au téléchargement 
.RE
.PP
\fBExceptions\fP
.RS 4
\fITreatmentException\fP en cas de fichier non téléchargeable 
.RE
.PP

.PP
Réimplémentée dans \fBFormFileManager\fP\&.
.PP
Définition à la ligne \fB61\fP du fichier \fBFileManager\&.php\fP\&.
.SS "storeIn (string $path, bool $createFoldersIfNotExists = \fCtrue\fP)"

.PP
Stock le fichier dans le dossier de stockage (en conservant le fichier actuel) 
.PP
\fBParamètres\fP
.RS 4
\fI$path\fP Chemin à partir du dossier de stockage comme racine (/) 
.br
\fI$createFoldersIfNotExists\fP si true et que le nouveau chemin contient des dossiers inexistants, ils seront créés 
.RE
.PP
\fBRenvoie\fP
.RS 4
bool si le stockage a réussi 
.RE
.PP

.PP
Réimplémentée dans \fBFormFileManager\fP\&.
.PP
Définition à la ligne \fB79\fP du fichier \fBFileManager\&.php\fP\&.
.SH "Documentation des champs"
.PP 
.SS "string $fileAbsolutePath\fC [protected]\fP"

.PP
Définition à la ligne \fB19\fP du fichier \fBFileManager\&.php\fP\&.

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Sabo final à partir du code source\&.
