.TH "SaboCore\Utils\Mailer" 3 "Mardi 23 Juillet 2024" "Version 1.1.1" "Sabo final" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SaboCore\Utils\Mailer
.SH SYNOPSIS
.br
.PP
.SS "Structures de données"

.in +1c
.ti -1c
.RI "class \fBBladeMailProvider\fP"
.br
.RI "Fournisseur de mail template blade\&. "
.ti -1c
.RI "class \fBMailerTemplateProvider\fP"
.br
.RI "Représente un fournisseur html pour mail à partir d'un template\&. "
.ti -1c
.RI "class \fBSaboMailer\fP"
.br
.RI "Helper d'envoi de mail simplifié "
.ti -1c
.RI "class \fBTwigMailProvider\fP"
.br
.RI "Fournisseur de mail template twig\&. "
.in -1c
.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Sabo final à partir du code source\&.
