.TH "SaboCore\Database\Default\Formatters" 3 "Mardi 23 Juillet 2024" "Version 1.1.1" "Sabo final" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SaboCore\Database\Default\Formatters
.SH SYNOPSIS
.br
.PP
.SS "Structures de données"

.in +1c
.ti -1c
.RI "interface \fBFormater\fP"
.br
.RI "Formateur de donnée\&. "
.ti -1c
.RI "class \fBFormaterException\fP"
.br
.RI "Exception d'échec de formatage\&. "
.ti -1c
.RI "class \fBJsonFormatter\fP"
.br
.RI "Formateur de donnée json en chaine json\&. "
.ti -1c
.RI "class \fBJsonReformer\fP"
.br
.RI "Reconstructeur de donnée json en chaine json\&. "
.in -1c
.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Sabo final à partir du code source\&.
