.TH "SaboCore\Database\System" 3 "Mardi 23 Juillet 2024" "Version 1.1.1" "Sabo final" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SaboCore\Database\System
.SH SYNOPSIS
.br
.PP
.SS "Structures de données"

.in +1c
.ti -1c
.RI "class \fBDatabaseActionException\fP"
.br
.RI "Exception d'action sur un processus de la base de données\&. "
.ti -1c
.RI "class \fBDatabaseComparator\fP"
.br
.RI "Représentation de la fonction de comparaison\&. "
.ti -1c
.RI "class \fBDatabaseCondition\fP"
.br
.RI "Condition de récupération\&. "
.ti -1c
.RI "class \fBDatabaseCondSeparator\fP"
.br
.RI "Représentation de la séparation entre deux conditions\&. "
.ti -1c
.RI "class \fBDatabaseModel\fP"
.br
.RI "Modèle de la base de données\&. "
.in -1c
.SS "Énumérations"

.in +1c
.ti -1c
.RI "enum \fBDatabaseActions\fP : int { \fBBEFORE_GENERATION\fP = 12 }"
.br
.RI "Actions de la base de données\&. "
.in -1c
.SH "Documentation du type de l'énumération"
.PP 
.SS "enum \fBDatabaseActions\fP : int"

.PP
Actions de la base de données\&. 
.PP
\fBAuteur\fP
.RS 4
yahaya bathily https://github.com/yahvya 
.RE
.PP

.PP
\fBValeurs énumérées\fP
.in +1c
.TP
\fB\fIBEFORE_GENERATION \fP\fP
Création du model en base de données\&. Actions avant création du model en base de données
.PP
Actions après création du model en base de données
.PP
Mise à jour du model en base de données
.PP
Actions avant mise à jour du model en base de données
.PP
Actions après mise à jour du model en base de données
.PP
Suppression du model en base de données
.PP
Actions avant suppression du model en base de données
.PP
Actions après suppression du model en base de données
.PP
Durant la génération du model
.PP
Après génération du model lors du find
.PP
Avant génération du model lors du find 
.PP
Définition à la ligne \fB9\fP du fichier \fBDatabaseActions\&.php\fP\&.
.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Sabo final à partir du code source\&.
