.TH "Request" 3 "Mardi 23 Juillet 2024" "Version 1.1.1" "Sabo final" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Request \- Gestionnaire des données de la requête\&.  

.SH SYNOPSIS
.br
.PP
.SS "Fonctions membres publiques"

.in +1c
.ti -1c
.RI "\fB__construct\fP ()"
.br
.ti -1c
.RI "\fBgetSessionStorage\fP ()"
.br
.ti -1c
.RI "\fBgetPostValues\fP (?string $errorMessage=null, string \&.\&.\&. $toGet)"
.br
.RI "Recherche des données post\&. "
.ti -1c
.RI "\fBgetGetValues\fP (?string $errorMessage=null, string \&.\&.\&. $toGet)"
.br
.RI "Recherche des données get\&. "
.ti -1c
.RI "\fBgetCookieValues\fP (?string $errorMessage=null, string \&.\&.\&. $toGet)"
.br
.RI "Recherche des données cookies\&. "
.ti -1c
.RI "\fBgetFilesValues\fP (?string $errorMessage=null, string \&.\&.\&. $toGet)"
.br
.RI "Recherche des données files\&. "
.ti -1c
.RI "\fBgetHeader\fP (string $header)"
.br
.RI "Fourni un en tête requête\&. "
.in -1c
.SS "Fonctions membres protégées statiques"

.in +1c
.ti -1c
.RI "static \fBgetValuesFrom\fP (array $container, string \&.\&.\&. $toGet)"
.br
.RI "Récupère les valeurs présentes dans un conteneur\&. "
.in -1c
.SS "Attributs protégés"

.in +1c
.ti -1c
.RI "\fBSessionStorage\fP \fB$sessionStorage\fP"
.br
.ti -1c
.RI "array \fB$headers\fP"
.br
.in -1c
.SH "Description détaillée"
.PP 
Gestionnaire des données de la requête\&. 


.PP
\fBAuteur\fP
.RS 4
yahaya bathily https://github.com/yahvya 
.RE
.PP

.PP
Définition à la ligne \fB13\fP du fichier \fBRequest\&.php\fP\&.
.SH "Documentation des constructeurs et destructeur"
.PP 
.SS "__construct ()"

.PP
Définition à la ligne \fB24\fP du fichier \fBRequest\&.php\fP\&.
.SH "Documentation des fonctions membres"
.PP 
.SS "getCookieValues (?string $errorMessage = \fCnull\fP, string \&.\&.\&. $toGet)"

.PP
Recherche des données cookies\&. 
.PP
\fBParamètres\fP
.RS 4
\fI$errorMessage\fP Si valeur non nulle une exception TreatmentException est levé en cas de clé non trouvée avec ce message displayable 
.br
\fIstring\fP \&.\&.\&.$toGet Les clés à chercher 
.RE
.PP
\fBRenvoie\fP
.RS 4
array|null Les valeurs trouvées indicées par leurs clés ou null si une clé non trouvée et message d'erreur null 
.RE
.PP
\fBExceptions\fP
.RS 4
\fITreatmentException\fP En cas de clé non trouvée et message d'erreur présent 
.RE
.PP

.PP
Définition à la ligne \fB84\fP du fichier \fBRequest\&.php\fP\&.
.SS "getFilesValues (?string $errorMessage = \fCnull\fP, string \&.\&.\&. $toGet)"

.PP
Recherche des données files\&. 
.PP
\fBParamètres\fP
.RS 4
\fI$errorMessage\fP Si valeur non nulle une exception TreatmentException est levé en cas de clé non trouvée avec ce message displayable 
.br
\fIstring\fP \&.\&.\&.$toGet Les clés à chercher 
.RE
.PP
\fBRenvoie\fP
.RS 4
array<string,FormFileManager>|null Les valeurs trouvées (sous forme de l'utilitaire FormFileManager) indicées par leurs clés ou null si une clé non trouvée et message d'erreur null 
.RE
.PP
\fBExceptions\fP
.RS 4
\fITreatmentException\fP En cas de clé non trouvée et message d'erreur présent 
.RE
.PP

.PP
Définition à la ligne \fB104\fP du fichier \fBRequest\&.php\fP\&.
.SS "getGetValues (?string $errorMessage = \fCnull\fP, string \&.\&.\&. $toGet)"

.PP
Recherche des données get\&. 
.PP
\fBParamètres\fP
.RS 4
\fI$errorMessage\fP Si valeur non nulle une exception TreatmentException est levé en cas de clé non trouvée avec ce message displayable 
.br
\fIstring\fP \&.\&.\&.$toGet Les clés à chercher 
.RE
.PP
\fBRenvoie\fP
.RS 4
array|null Les valeurs trouvées indicées par leurs clés ou null si une clé non trouvée et message d'erreur null 
.RE
.PP
\fBExceptions\fP
.RS 4
\fITreatmentException\fP En cas de clé non trouvée et message d'erreur présent 
.RE
.PP

.PP
Définition à la ligne \fB64\fP du fichier \fBRequest\&.php\fP\&.
.SS "getHeader (string $header)"

.PP
Fourni un en tête requête\&. 
.PP
\fBParamètres\fP
.RS 4
\fI$header\fP nom de l'en tête 
.RE
.PP
\fBRenvoie\fP
.RS 4
string|null l'en-tête ou null si non trouvé 
.RE
.PP

.PP
Définition à la ligne \fB126\fP du fichier \fBRequest\&.php\fP\&.
.SS "getPostValues (?string $errorMessage = \fCnull\fP, string \&.\&.\&. $toGet)"

.PP
Recherche des données post\&. 
.PP
\fBParamètres\fP
.RS 4
\fI$errorMessage\fP Si valeur non nulle une exception TreatmentException est levé en cas de clé non trouvée avec ce message displayable 
.br
\fIstring\fP \&.\&.\&.$toGet Les clés à chercher 
.RE
.PP
\fBRenvoie\fP
.RS 4
array|null Les valeurs trouvées indicées par leurs clés ou null si une clé non trouvée et message d'erreur null 
.RE
.PP
\fBExceptions\fP
.RS 4
\fITreatmentException\fP En cas de clé non trouvée et message d'erreur présent 
.RE
.PP

.PP
Définition à la ligne \fB44\fP du fichier \fBRequest\&.php\fP\&.
.SS "getSessionStorage ()"

.PP
\fBRenvoie\fP
.RS 4
SessionStorage le gestionnaire de stockage de la session 
.RE
.PP

.PP
Définition à la ligne \fB33\fP du fichier \fBRequest\&.php\fP\&.
.SS "static getValuesFrom (array $container, string \&.\&.\&. $toGet)\fC [static]\fP, \fC [protected]\fP"

.PP
Récupère les valeurs présentes dans un conteneur\&. 
.PP
\fBParamètres\fP
.RS 4
\fI$container\fP le conteneur 
.br
\fIstring\fP \&.\&.\&.$toGet clé à rechercher 
.RE
.PP
\fBRenvoie\fP
.RS 4
array|null le tableau des valeurs trouvées ou null si une des clés n'a pas été trouvée 
.RE
.PP

.PP
Définition à la ligne \fB136\fP du fichier \fBRequest\&.php\fP\&.
.SH "Documentation des champs"
.PP 
.SS "array $headers\fC [protected]\fP"

.PP
Définition à la ligne \fB22\fP du fichier \fBRequest\&.php\fP\&.
.SS "\fBSessionStorage\fP $sessionStorage\fC [protected]\fP"

.PP
Définition à la ligne \fB17\fP du fichier \fBRequest\&.php\fP\&.

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Sabo final à partir du code source\&.
