.TH "CallableCond" 3 "Mardi 23 Juillet 2024" "Version 1.1.1" "Sabo final" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CallableCond \- Représente une condition pouvant être appellé  

.SH SYNOPSIS
.br
.PP
.PP
Est dérivée de \fBCond\fP\&.
.SS "Fonctions membres publiques"

.in +1c
.ti -1c
.RI "\fB__construct\fP (callable $toVerify, string $errorMessage, bool $isDisplayable)"
.br
.ti -1c
.RI "\fBverifyData\fP (\fBMysqlModel\fP $baseModel, string $attributeName, mixed $data)"
.br
.RI "Vérifie si la donnée est valide\&. "
.ti -1c
.RI "\fBgetIsDisplayable\fP ()"
.br
.ti -1c
.RI "\fBgetErrorMessage\fP ()"
.br
.in -1c
.in +1c
.ti -1c
.RI "\fBverifyData\fP (\fBMysqlModel\fP $baseModel, string $attributeName, mixed $data)"
.br
.RI "Vérifie si la donnée est valide\&. "
.ti -1c
.RI "\fBgetErrorMessage\fP ()"
.br
.ti -1c
.RI "\fBgetIsDisplayable\fP ()"
.br
.in -1c
.SH "Description détaillée"
.PP 
Représente une condition pouvant être appellé 


.PP
\fBAuteur\fP
.RS 4
yahaya bathily https://github.com/yahvya 
.RE
.PP

.PP
Définition à la ligne \fB15\fP du fichier \fBCallableCond\&.php\fP\&.
.SH "Documentation des constructeurs et destructeur"
.PP 
.SS "__construct (callable $toVerify, string $errorMessage, bool $isDisplayable)"

.PP
\fBParamètres\fP
.RS 4
\fI$toVerify\fP le callable à vérifier, doit renvoyer un booléen 
.br
\fI$errorMessage\fP le message d'erreur 
.br
\fI$isDisplayable\fP défini si l'erreur peut être affichée 
.RE
.PP

.PP
Définition à la ligne \fB36\fP du fichier \fBCallableCond\&.php\fP\&.
.SH "Documentation des fonctions membres"
.PP 
.SS "getErrorMessage ()"

.PP
\fBRenvoie\fP
.RS 4
string Le message d'erreur 
.RE
.PP

.PP
Implémente \fBCond\fP\&.
.PP
Définition à la ligne \fB53\fP du fichier \fBCallableCond\&.php\fP\&.
.SS "getIsDisplayable ()"

.PP
\fBRenvoie\fP
.RS 4
bool Si le message d'erreur peut être affiché 
.RE
.PP

.PP
Implémente \fBCond\fP\&.
.PP
Définition à la ligne \fB48\fP du fichier \fBCallableCond\&.php\fP\&.
.SS "verifyData (\fBMysqlModel\fP $baseModel, string $attributeName, mixed $data)"

.PP
Vérifie si la donnée est valide\&. 
.PP
\fBParamètres\fP
.RS 4
\fI$baseModel\fP Model de base 
.br
\fI$attributeName\fP Nom de l'attribut 
.br
\fI$data\fP donnée à vérifier 
.RE
.PP
\fBRenvoie\fP
.RS 4
bool si la donnée est valide 
.RE
.PP

.PP
Implémente \fBCond\fP\&.
.PP
Définition à la ligne \fB43\fP du fichier \fBCallableCond\&.php\fP\&.

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Sabo final à partir du code source\&.
