.TH "SaboCommand" 3 "Mardi 23 Juillet 2024" "Version 1.1.1" "Sabo final" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SaboCommand \- Commande\&.  

.SH SYNOPSIS
.br
.PP
.PP
Dérivée par \fBHelpCommand\fP, \fBLaunchServerCommand\fP, et \fBSaboTemplateUserCommand\fP\&.
.SS "Fonctions membres publiques"

.in +1c
.ti -1c
.RI "\fB__construct\fP (string $commandName)"
.br
.ti -1c
.RI "\fBgetName\fP ()"
.br
.ti -1c
.RI "\fBexecCommand\fP (\fBSaboCli\fP $cli)"
.br
.RI "Exécute la commande\&. "
.ti -1c
.RI "\fBgetHelpLines\fP ()"
.br
.in -1c
.SS "Fonctions membres protégées"

.in +1c
.ti -1c
.RI "\fBgetOptions\fP (\fBSaboCli\fP $cli, string \&.\&.\&. $optionNames)"
.br
.RI "Récupère les valeurs des options recherchées ou les demandes si non trouvées\&. "
.ti -1c
.RI "\fBask\fP (string $toAsk, \fBConfig\fP $themeConfig)"
.br
.RI "Pose une question\&. "
.in -1c
.SS "Attributs protégés"

.in +1c
.ti -1c
.RI "string \fB$commandName\fP"
.br
.in -1c
.SH "Description détaillée"
.PP 
Commande\&. 


.PP
\fBAuteur\fP
.RS 4
yahaya bathily https://github.com/yahvya/ 
.RE
.PP

.PP
Définition à la ligne \fB17\fP du fichier \fBSaboCommand\&.php\fP\&.
.SH "Documentation des constructeurs et destructeur"
.PP 
.SS "__construct (string $commandName)"

.PP
\fBParamètres\fP
.RS 4
\fI$commandName\fP nom de la commande 
.RE
.PP

.PP
Définition à la ligne \fB26\fP du fichier \fBSaboCommand\&.php\fP\&.
.SH "Documentation des fonctions membres"
.PP 
.SS "ask (string $toAsk, \fBConfig\fP $themeConfig)\fC [protected]\fP"

.PP
Pose une question\&. 
.PP
\fBParamètres\fP
.RS 4
\fI$toAsk\fP la question 
.br
\fI$themeConfig\fP configuration de thème 
.RE
.PP
\fBRenvoie\fP
.RS 4
string la réponse saisie 
.RE
.PP
\fBExceptions\fP
.RS 4
\fIConfigException\fP en cas d'erreur de thème 
.RE
.PP

.PP
Définition à la ligne \fB68\fP du fichier \fBSaboCommand\&.php\fP\&.
.SS "execCommand (\fBSaboCli\fP $cli)\fC [abstract]\fP"

.PP
Exécute la commande\&. 
.PP
\fBParamètres\fP
.RS 4
\fI$cli\fP le gestionnaire cli lié 
.RE
.PP
\fBExceptions\fP
.RS 4
\fIConfigException|Throwable\fP en cas d'erreur interne 
.RE
.PP
\fBRenvoie\fP
.RS 4
void 
.RE
.PP

.PP
Réimplémentée dans \fBControllerMakerCommand\fP, \fBHelpCommand\fP, \fBLaunchServerCommand\fP, et \fBModelMakerCommand\fP\&.
.SS "getHelpLines ()\fC [abstract]\fP"

.PP
\fBRenvoie\fP
.RS 4
string[] les lignes à afficher pour l'aide de la commande 
.RE
.PP

.PP
Réimplémentée dans \fBControllerMakerCommand\fP, \fBHelpCommand\fP, \fBLaunchServerCommand\fP, et \fBModelMakerCommand\fP\&.
.SS "getName ()"

.PP
\fBRenvoie\fP
.RS 4
string le nom de la commande 
.RE
.PP

.PP
Définition à la ligne \fB33\fP du fichier \fBSaboCommand\&.php\fP\&.
.SS "getOptions (\fBSaboCli\fP $cli, string \&.\&.\&. $optionNames)\fC [protected]\fP"

.PP
Récupère les valeurs des options recherchées ou les demandes si non trouvées\&. 
.PP
\fBAttention\fP
.RS 4
à utiliser pour les options obligatoires 
.RE
.PP
\fBParamètres\fP
.RS 4
\fI$cli\fP Cli 
.br
\fIstring\fP \&.\&.\&.$optionNames nom des options recherchées 
.RE
.PP
\fBRenvoie\fP
.RS 4
array Les options au format ['nom option' → 'valuer option'] 
.RE
.PP
\fBExceptions\fP
.RS 4
\fIConfigException\fP en cas d'erreur 
.RE
.PP

.PP
Définition à la ligne \fB45\fP du fichier \fBSaboCommand\&.php\fP\&.
.SH "Documentation des champs"
.PP 
.SS "string $commandName\fC [protected]\fP"

.PP
Définition à la ligne \fB21\fP du fichier \fBSaboCommand\&.php\fP\&.

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Sabo final à partir du code source\&.
