.TH "SaboTemplateUserCommand" 3 "Mardi 23 Juillet 2024" "Version 1.1.1" "Sabo final" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SaboTemplateUserCommand \- Commande de template d'un template\&.  

.SH SYNOPSIS
.br
.PP
.PP
Est dérivée de \fBSaboCommand\fP\&.
.PP
Dérivée par \fBControllerMakerCommand\fP, et \fBModelMakerCommand\fP\&.
.SS "Fonctions membres publiques statiques"

.in +1c
.ti -1c
.RI "static \fBgetCliRoot\fP ()"
.br
.ti -1c
.RI "static \fBformatNameForClass\fP (string $baseName)"
.br
.RI "Formate le nom fourni au format class\&. "
.ti -1c
.RI "static \fBfindClassDatas\fP (string $className, string $from)"
.br
.RI "Recherche le namespace et le dossier d'une class (psr-4) à partir du dossier fourni récursivement\&. "
.in -1c
.SS "Champs de données"

.in +1c
.ti -1c
.RI "const string \fBTEMPLATES_DIR_PATH\fP = '/storage/templates'"
.br
.in -1c
.SS "Fonctions membres protégées"

.in +1c
.ti -1c
.RI "\fBcreateFromTemplate\fP (string $templatePath, string $dstPath, array $replacements)"
.br
.RI "Crée un fichier à partir d'un template\&. "
.in -1c

Fonctions membres protégées hérités de \fBSaboCommand\fP
.in +1c
.ti -1c
.RI "\fBgetOptions\fP (\fBSaboCli\fP $cli, string \&.\&.\&. $optionNames)"
.br
.RI "Récupère les valeurs des options recherchées ou les demandes si non trouvées\&. "
.ti -1c
.RI "\fBask\fP (string $toAsk, \fBConfig\fP $themeConfig)"
.br
.RI "Pose une question\&. "
.in -1c
.SS "Membres hérités additionnels"


Fonctions membres publiques hérités de \fBSaboCommand\fP
.in +1c
.ti -1c
.RI "\fB__construct\fP (string $commandName)"
.br
.ti -1c
.RI "\fBgetName\fP ()"
.br
.ti -1c
.RI "\fBexecCommand\fP (\fBSaboCli\fP $cli)"
.br
.RI "Exécute la commande\&. "
.ti -1c
.RI "\fBgetHelpLines\fP ()"
.br
.in -1c

Attributs protégés hérités de \fBSaboCommand\fP
.in +1c
.ti -1c
.RI "string \fB$commandName\fP"
.br
.in -1c
.SH "Description détaillée"
.PP 
Commande de template d'un template\&. 


.PP
\fBAuteur\fP
.RS 4
yahaya bathily https://github.com/yahvya/ 
.RE
.PP

.PP
Définition à la ligne \fB12\fP du fichier \fBSaboTemplateUserCommand\&.php\fP\&.
.SH "Documentation des fonctions membres"
.PP 
.SS "createFromTemplate (string $templatePath, string $dstPath, array $replacements)\fC [protected]\fP"

.PP
Crée un fichier à partir d'un template\&. 
.PP
\fBParamètres\fP
.RS 4
\fI$templatePath\fP Chemin du template à partir du dossier de stockage des templates 
.br
\fI$dstPath\fP Chemin absolu de destination du fichier 
.br
\fI$replacements\fP données à remplacer dans le template au format ['clé' → 'remplacement'] 
.RE
.PP
\fBRenvoie\fP
.RS 4
bool Si la création a bien réussi 
.RE
.PP

.PP
Définition à la ligne \fB25\fP du fichier \fBSaboTemplateUserCommand\&.php\fP\&.
.SS "static findClassDatas (string $className, string $from)\fC [static]\fP"

.PP
Recherche le namespace et le dossier d'une class (psr-4) à partir du dossier fourni récursivement\&. 
.PP
\fBParamètres\fP
.RS 4
\fI$className\fP Nom de la class 
.br
\fI$from\fP Chemin de départ de recherche 
.RE
.PP
\fBRenvoie\fP
.RS 4
array|null null si non trouvé ou, données au format ['namespace' → '\&.\&.\&.' ou null si non trouvé,'directory' → '\&.\&.\&.'] 
.RE
.PP

.PP
Définition à la ligne \fB72\fP du fichier \fBSaboTemplateUserCommand\&.php\fP\&.
.SS "static formatNameForClass (string $baseName)\fC [static]\fP"

.PP
Formate le nom fourni au format class\&. 
.PP
\fBParamètres\fP
.RS 4
\fI$baseName\fP nom de base 
.RE
.PP
\fBRenvoie\fP
.RS 4
string Le nom formaté 
.RE
.PP

.PP
Définition à la ligne \fB56\fP du fichier \fBSaboTemplateUserCommand\&.php\fP\&.
.SS "static getCliRoot ()\fC [static]\fP"

.PP
\fBRenvoie\fP
.RS 4
string Le chemin root du dossier cli 
.RE
.PP
\fBExceptions\fP
.RS 4
\fIConfigException\fP en cas d'erreur de configuration 
.RE
.PP

.PP
Définition à la ligne \fB47\fP du fichier \fBSaboTemplateUserCommand\&.php\fP\&.
.SH "Documentation des champs"
.PP 
.SS "const string TEMPLATES_DIR_PATH = '/storage/templates'"
@const string Chemin du dossier des templates 
.PP
Définition à la ligne \fB16\fP du fichier \fBSaboTemplateUserCommand\&.php\fP\&.

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Sabo final à partir du code source\&.
