.TH "SaboCore\Database\Default\Conditions" 3 "Mardi 23 Juillet 2024" "Version 1.1.1" "Sabo final" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SaboCore\Database\Default\Conditions
.SH SYNOPSIS
.br
.PP
.SS "Structures de données"

.in +1c
.ti -1c
.RI "class \fBCallableCond\fP"
.br
.RI "Représente une condition pouvant être appellé "
.ti -1c
.RI "interface \fBCond\fP"
.br
.RI "Représente une condition de validation\&. "
.ti -1c
.RI "class \fBDateTimeCond\fP"
.br
.RI "Condition représentant un champ de type datetime\&. "
.ti -1c
.RI "class \fBEnumValidityCond\fP"
.br
.RI "Vérifie la possibilité d'utiliser la donnée\&. "
.ti -1c
.RI "class \fBFilterCond\fP"
.br
.RI "Condition filter_var\&. "
.ti -1c
.RI "class \fBJsonValidityCond\fP"
.br
.RI "Condition de vérification de validité json\&. "
.ti -1c
.RI "class \fBLenCond\fP"
.br
.RI "Condition de vérification de taille\&. "
.ti -1c
.RI "class \fBMysqlCondException\fP"
.br
.RI "Exception de non-validité de condition\&. "
.ti -1c
.RI "class \fBRegexCond\fP"
.br
.RI "Attribut définissant une condition regex\&. "
.in -1c
.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Sabo final à partir du code source\&.
