.TH "SaboCore\Utils\String" 3 "Mardi 23 Juillet 2024" "Version 1.1.1" "Sabo final" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SaboCore\Utils\String
.SH SYNOPSIS
.br
.PP
.SS "Structures de données"

.in +1c
.ti -1c
.RI "class \fBRandomStringGenerator\fP"
.br
.RI "Générateur de chaine aléatoire\&. "
.in -1c
.SS "Énumérations"

.in +1c
.ti -1c
.RI "enum \fBRandomStringType\fP : string { \fBSPECIALCHARS\fP = 'specialchars' }"
.br
.in -1c
.SH "Documentation du type de l'énumération"
.PP 
.SS "enum \fBRandomStringType\fP : string"
liste les types de caractères utilisables 
.PP
\fBValeurs énumérées\fP
.in +1c
.TP
\fB\fISPECIALCHARS \fP\fP
caractères majuscules caractères minuscules nombres caractère spéciaux 
.PP
Définition à la ligne \fB8\fP du fichier \fBRandomStringType\&.php\fP\&.
.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Sabo final à partir du code source\&.
