.TH "Cond" 3 "Mardi 23 Juillet 2024" "Version 1.1.1" "Sabo final" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Cond \- Représente une condition de validation\&.  

.SH SYNOPSIS
.br
.PP
.PP
Dérivée par \fBCallableCond\fP, \fBDateTimeCond\fP, \fBEnumValidityCond\fP, \fBFilterCond\fP, \fBJsonValidityCond\fP, \fBLenCond\fP, et \fBRegexCond\fP\&.
.SS "Fonctions membres publiques"

.in +1c
.ti -1c
.RI "\fBverifyData\fP (\fBMysqlModel\fP $baseModel, string $attributeName, mixed $data)"
.br
.RI "Vérifie si la donnée est valide\&. "
.ti -1c
.RI "\fBgetErrorMessage\fP ()"
.br
.ti -1c
.RI "\fBgetIsDisplayable\fP ()"
.br
.in -1c
.SH "Description détaillée"
.PP 
Représente une condition de validation\&. 
.PP
Définition à la ligne \fB10\fP du fichier \fBCond\&.php\fP\&.
.SH "Documentation des fonctions membres"
.PP 
.SS "getErrorMessage ()"

.PP
\fBRenvoie\fP
.RS 4
string Le message d'erreur 
.RE
.PP

.PP
Implémenté dans \fBCallableCond\fP, \fBDateTimeCond\fP, \fBEnumValidityCond\fP, \fBFilterCond\fP, \fBJsonValidityCond\fP, \fBLenCond\fP, et \fBRegexCond\fP\&.
.SS "getIsDisplayable ()"

.PP
\fBRenvoie\fP
.RS 4
bool Si le message d'erreur peut être affiché 
.RE
.PP

.PP
Implémenté dans \fBCallableCond\fP, \fBDateTimeCond\fP, \fBEnumValidityCond\fP, \fBFilterCond\fP, \fBJsonValidityCond\fP, \fBLenCond\fP, et \fBRegexCond\fP\&.
.SS "verifyData (\fBMysqlModel\fP $baseModel, string $attributeName, mixed $data)"

.PP
Vérifie si la donnée est valide\&. 
.PP
\fBParamètres\fP
.RS 4
\fI$baseModel\fP Model de base 
.br
\fI$attributeName\fP Nom de l'attribut 
.br
\fI$data\fP donnée à vérifier 
.RE
.PP
\fBRenvoie\fP
.RS 4
bool si la donnée est valide 
.RE
.PP

.PP
Implémenté dans \fBCallableCond\fP, \fBDateTimeCond\fP, \fBEnumValidityCond\fP, \fBFilterCond\fP, \fBJsonValidityCond\fP, \fBLenCond\fP, et \fBRegexCond\fP\&.

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Sabo final à partir du code source\&.
