.TH "Controller" 3 "Mardi 23 Juillet 2024" "Version 1.1.1" "Sabo final" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Controller \- Controller abstrait\&.  

.SH SYNOPSIS
.br
.PP
.PP
Dérivée par \fBCustomController\fP, et \fBMaintenanceController\fP\&.
.SS "Fonctions membres publiques"

.in +1c
.ti -1c
.RI "\fB__construct\fP ()"
.br
.in -1c
.SH "Description détaillée"
.PP 
Controller abstrait\&. 


.PP
\fBAuteur\fP
.RS 4
yahaya bathily https://github.com/yahvya 
.RE
.PP

.PP
Définition à la ligne \fB9\fP du fichier \fBController\&.php\fP\&.
.SH "Documentation des constructeurs et destructeur"
.PP 
.SS "__construct ()"

.PP
Réimplémentée dans \fBMaintenanceController\fP\&.
.PP
Définition à la ligne \fB10\fP du fichier \fBController\&.php\fP\&.

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Sabo final à partir du code source\&.
