.TH "SaboCore\Utils\Sse" 3 "Mardi 23 Juillet 2024" "Version 1.1.1" "Sabo final" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SaboCore\Utils\Sse
.SH SYNOPSIS
.br
.PP
.SS "Structures de données"

.in +1c
.ti -1c
.RI "class \fBResourceManager\fP"
.br
.RI "Gestinonaire de ressource\&. "
.ti -1c
.RI "class \fBSaboSse\fP"
.br
.RI "Utilitaire d'évènement sse\&. "
.in -1c
.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Sabo final à partir du code source\&.
