.TH "ConfigException" 3 "Mardi 23 Juillet 2024" "Version 1.1.1" "Sabo final" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ConfigException \- Exception de configuration\&.  

.SH SYNOPSIS
.br
.PP
.PP
Est dérivée de Exception\&.
.SH "Description détaillée"
.PP 
Exception de configuration\&. 


.PP
\fBAuteur\fP
.RS 4
yahaya bathily https://github.com/yahvya/ 
.RE
.PP

.PP
Définition à la ligne \fB11\fP du fichier \fBConfigException\&.php\fP\&.

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Sabo final à partir du code source\&.
