.TH "DateTimeCond" 3 "Mardi 23 Juillet 2024" "Version 1.1.1" "Sabo final" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DateTimeCond \- Condition représentant un champ de type datetime\&.  

.SH SYNOPSIS
.br
.PP
.PP
Est dérivée de \fBCond\fP\&.
.SS "Fonctions membres publiques"

.in +1c
.ti -1c
.RI "\fB__construct\fP (string $errorMessage='Une date au format correct est attendue')"
.br
.ti -1c
.RI "\fBverifyData\fP (\fBMysqlModel\fP $baseModel, string $attributeName, mixed $data)"
.br
.RI "Vérifie si la donnée est valide\&. "
.ti -1c
.RI "\fBgetIsDisplayable\fP ()"
.br
.ti -1c
.RI "\fBgetErrorMessage\fP ()"
.br
.in -1c
.in +1c
.ti -1c
.RI "\fBverifyData\fP (\fBMysqlModel\fP $baseModel, string $attributeName, mixed $data)"
.br
.RI "Vérifie si la donnée est valide\&. "
.ti -1c
.RI "\fBgetErrorMessage\fP ()"
.br
.ti -1c
.RI "\fBgetIsDisplayable\fP ()"
.br
.in -1c
.SH "Description détaillée"
.PP 
Condition représentant un champ de type datetime\&. 


.PP
\fBAuteur\fP
.RS 4
yahaya bathily https://github.com/yahvya 
.RE
.PP

.PP
Définition à la ligne \fB16\fP du fichier \fBDateTimeCond\&.php\fP\&.
.SH "Documentation des constructeurs et destructeur"
.PP 
.SS "__construct (string $errorMessage = \fC'Une date au format correct est attendue'\fP)"

.PP
\fBParamètres\fP
.RS 4
\fI$errorMessage\fP le message d'erreur affiché 
.RE
.PP

.PP
Définition à la ligne \fB25\fP du fichier \fBDateTimeCond\&.php\fP\&.
.SH "Documentation des fonctions membres"
.PP 
.SS "getErrorMessage ()"

.PP
\fBRenvoie\fP
.RS 4
string Le message d'erreur 
.RE
.PP

.PP
Implémente \fBCond\fP\&.
.PP
Définition à la ligne \fB47\fP du fichier \fBDateTimeCond\&.php\fP\&.
.SS "getIsDisplayable ()"

.PP
\fBRenvoie\fP
.RS 4
bool Si le message d'erreur peut être affiché 
.RE
.PP

.PP
Implémente \fBCond\fP\&.
.PP
Définition à la ligne \fB42\fP du fichier \fBDateTimeCond\&.php\fP\&.
.SS "verifyData (\fBMysqlModel\fP $baseModel, string $attributeName, mixed $data)"

.PP
Vérifie si la donnée est valide\&. 
.PP
\fBParamètres\fP
.RS 4
\fI$baseModel\fP Model de base 
.br
\fI$attributeName\fP Nom de l'attribut 
.br
\fI$data\fP donnée à vérifier 
.RE
.PP
\fBRenvoie\fP
.RS 4
bool si la donnée est valide 
.RE
.PP

.PP
Implémente \fBCond\fP\&.
.PP
Définition à la ligne \fB30\fP du fichier \fBDateTimeCond\&.php\fP\&.

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Sabo final à partir du code source\&.
