.TH "Storable" 3 "Mardi 23 Juillet 2024" "Version 1.1.1" "Sabo final" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Storable \- Représente un élement pouvant être stocké  

.SH SYNOPSIS
.br
.PP
.PP
Dérivée par \fBFileManager\fP\&.
.SS "Fonctions membres publiques"

.in +1c
.ti -1c
.RI "\fBstoreIn\fP (string $path)"
.br
.RI "Stocke l'élément\&. "
.ti -1c
.RI "\fBgetFromStorage\fP ()"
.br
.in -1c
.SH "Description détaillée"
.PP 
Représente un élement pouvant être stocké 


.PP
\fBAuteur\fP
.RS 4
yahaya bathily 
.RE
.PP

.PP
Définition à la ligne \fB9\fP du fichier \fBStorable\&.php\fP\&.
.SH "Documentation des fonctions membres"
.PP 
.SS "getFromStorage ()"

.PP
\fBRenvoie\fP
.RS 4
mixed le contenu de l'élément stocké 
.RE
.PP

.PP
Implémenté dans \fBFileManager\fP, et \fBFormFileManager\fP\&.
.SS "storeIn (string $path)"

.PP
Stocke l'élément\&. 
.PP
\fBParamètres\fP
.RS 4
\fI$path\fP chemin de stockage attendu 
.RE
.PP
\fBRenvoie\fP
.RS 4
bool si le stockage a réussi 
.RE
.PP


.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Sabo final à partir du code source\&.
