.TH "HelpCommand" 3 "Mardi 23 Juillet 2024" "Version 1.1.1" "Sabo final" \" -*- nroff -*-
.ad l
.nh
.SH NAME
HelpCommand \- Commande d'affichage d'aide\&.  

.SH SYNOPSIS
.br
.PP
.PP
Est dérivée de \fBSaboCommand\fP\&.
.SS "Fonctions membres publiques"

.in +1c
.ti -1c
.RI "\fBexecCommand\fP (\fBSaboCli\fP $cli)"
.br
.RI "Exécute la commande\&. "
.ti -1c
.RI "\fBgetHelpLines\fP ()"
.br
.in -1c

Fonctions membres publiques hérités de \fBSaboCommand\fP
.in +1c
.ti -1c
.RI "\fB__construct\fP (string $commandName)"
.br
.ti -1c
.RI "\fBgetName\fP ()"
.br
.ti -1c
.RI "\fBexecCommand\fP (\fBSaboCli\fP $cli)"
.br
.RI "Exécute la commande\&. "
.ti -1c
.RI "\fBgetHelpLines\fP ()"
.br
.in -1c
.SS "Membres hérités additionnels"


Fonctions membres protégées hérités de \fBSaboCommand\fP
.in +1c
.ti -1c
.RI "\fBgetOptions\fP (\fBSaboCli\fP $cli, string \&.\&.\&. $optionNames)"
.br
.RI "Récupère les valeurs des options recherchées ou les demandes si non trouvées\&. "
.ti -1c
.RI "\fBask\fP (string $toAsk, \fBConfig\fP $themeConfig)"
.br
.RI "Pose une question\&. "
.in -1c

Attributs protégés hérités de \fBSaboCommand\fP
.in +1c
.ti -1c
.RI "string \fB$commandName\fP"
.br
.in -1c
.SH "Description détaillée"
.PP 
Commande d'affichage d'aide\&. 


.PP
\fBAuteur\fP
.RS 4
yahaya bathily https://github.com/yahvya/ 
.RE
.PP

.PP
Définition à la ligne \fB14\fP du fichier \fBHelpCommand\&.php\fP\&.
.SH "Documentation des fonctions membres"
.PP 
.SS "execCommand (\fBSaboCli\fP $cli)"

.PP
Exécute la commande\&. 
.PP
\fBParamètres\fP
.RS 4
\fI$cli\fP le gestionnaire cli lié 
.RE
.PP
\fBExceptions\fP
.RS 4
\fIConfigException|Throwable\fP en cas d'erreur interne 
.RE
.PP
\fBRenvoie\fP
.RS 4
void 
.RE
.PP

.PP
Réimplémentée à partir de \fBSaboCommand\fP\&.
.PP
Définition à la ligne \fB16\fP du fichier \fBHelpCommand\&.php\fP\&.
.SS "getHelpLines ()"

.PP
\fBRenvoie\fP
.RS 4
string[] les lignes à afficher pour l'aide de la commande 
.RE
.PP

.PP
Réimplémentée à partir de \fBSaboCommand\fP\&.
.PP
Définition à la ligne \fB72\fP du fichier \fBHelpCommand\&.php\fP\&.

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Sabo final à partir du code source\&.
