.TH "SaboCore\Database\Default\CustomDatatypes" 3 "Mardi 23 Juillet 2024" "Version 1.1.1" "Sabo final" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SaboCore\Database\Default\CustomDatatypes
.SH SYNOPSIS
.br
.PP
.SS "Structures de données"

.in +1c
.ti -1c
.RI "class \fBJoinedList\fP"
.br
.RI "Lignes jointes\&. "
.ti -1c
.RI "class \fBTimestamp\fP"
.br
.RI "Type custom timestamp\&. "
.in -1c
.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Sabo final à partir du code source\&.
