.TH "Response" 3 "Mardi 23 Juillet 2024" "Version 1.1.1" "Sabo final" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Response \- Gestionnaire de retour de réponse\&.  

.SH SYNOPSIS
.br
.PP
.PP
Dérivée par \fBDownloadResponse\fP, \fBHtmlResponse\fP, \fBJsonResponse\fP, \fBRedirectResponse\fP, et \fBResourceResponse\fP\&.
.SS "Fonctions membres publiques"

.in +1c
.ti -1c
.RI "\fBsetHeader\fP (string $name, string $value)"
.br
.RI "Ajoute un en-tête à la réponse\&. "
.ti -1c
.RI "\fBsetContent\fP (mixed $content)"
.br
.RI "Met à jour le contenu de la réponse\&. "
.ti -1c
.RI "\fBsetResponseCode\fP (\fBResponseCode\fP $code)"
.br
.RI "Met à jour le code réponse\&. "
.ti -1c
.RI "\fBgetHeaders\fP ()"
.br
.ti -1c
.RI "\fBgetContent\fP ()"
.br
.ti -1c
.RI "\fBgetResponseCode\fP ()"
.br
.ti -1c
.RI "\fBrenderResponse\fP ()"
.br
.RI "Rend la réponse entière\&. "
.in -1c
.SS "Fonctions membres protégées"

.in +1c
.ti -1c
.RI "\fBrenderContent\fP ()"
.br
.RI "Rend le contenu de la réponse\&. "
.in -1c
.SS "Attributs protégés"

.in +1c
.ti -1c
.RI "\fBResponseCode\fP \fB$responseCode\fP = ResponseCode::OK"
.br
.ti -1c
.RI "mixed \fB$content\fP = null"
.br
.ti -1c
.RI "array \fB$headers\fP"
.br
.in -1c
.SH "Description détaillée"
.PP 
Gestionnaire de retour de réponse\&. 


.PP
\fBAuteur\fP
.RS 4
yahaya bathily https://github.com/yahvya 
.RE
.PP

.PP
Définition à la ligne \fB9\fP du fichier \fBResponse\&.php\fP\&.
.SH "Documentation des fonctions membres"
.PP 
.SS "getContent ()"

.PP
\fBRenvoie\fP
.RS 4
mixed le contenu de la réponse 
.RE
.PP

.PP
Définition à la ligne \fB73\fP du fichier \fBResponse\&.php\fP\&.
.SS "getHeaders ()"

.PP
\fBRenvoie\fP
.RS 4
array<string,string> les en-têtes 
.RE
.PP

.PP
Définition à la ligne \fB66\fP du fichier \fBResponse\&.php\fP\&.
.SS "getResponseCode ()"

.PP
\fBRenvoie\fP
.RS 4
ResponseCode le code réponse 
.RE
.PP

.PP
Définition à la ligne \fB80\fP du fichier \fBResponse\&.php\fP\&.
.SS "renderContent ()\fC [protected]\fP"

.PP
Rend le contenu de la réponse\&. 
.PP
\fBRenvoie\fP
.RS 4
never 
.RE
.PP

.PP
Réimplémentée dans \fBDownloadResponse\fP, \fBHtmlResponse\fP, \fBJsonResponse\fP, et \fBResourceResponse\fP\&.
.PP
Définition à la ligne \fB88\fP du fichier \fBResponse\&.php\fP\&.
.SS "renderResponse ()"

.PP
Rend la réponse entière\&. 
.PP
\fBRenvoie\fP
.RS 4
never 
.RE
.PP

.PP
Définition à la ligne \fB96\fP du fichier \fBResponse\&.php\fP\&.
.SS "setContent (mixed $content)"

.PP
Met à jour le contenu de la réponse\&. 
.PP
\fBParamètres\fP
.RS 4
\fI$content\fP contenu de la réponse 
.RE
.PP
\fBRenvoie\fP
.RS 4
$this 
.RE
.PP

.PP
Définition à la ligne \fB46\fP du fichier \fBResponse\&.php\fP\&.
.SS "setHeader (string $name, string $value)"

.PP
Ajoute un en-tête à la réponse\&. 
.PP
\fBParamètres\fP
.RS 4
\fI$name\fP nom de l'en-tête 
.br
\fI$value\fP valeur associée 
.RE
.PP
\fBRenvoie\fP
.RS 4
$this 
.RE
.PP

.PP
Définition à la ligne \fB35\fP du fichier \fBResponse\&.php\fP\&.
.SS "setResponseCode (\fBResponseCode\fP $code)"

.PP
Met à jour le code réponse\&. 
.PP
\fBParamètres\fP
.RS 4
\fI$code\fP code réponse 
.RE
.PP
\fBRenvoie\fP
.RS 4
$this 
.RE
.PP

.PP
Définition à la ligne \fB57\fP du fichier \fBResponse\&.php\fP\&.
.SH "Documentation des champs"
.PP 
.SS "mixed $content = null\fC [protected]\fP"

.PP
Définition à la ligne \fB18\fP du fichier \fBResponse\&.php\fP\&.
.SS "array $headers\fC [protected]\fP"
\fBValeur initiale :\fP.PP
.nf
= [
        "X\-Content\-Type\-Options" => "nosniff",
        "Cache\-Control" => "no\-cache, no\-store, must\-revalidate",
        "Strict\-Transport\-Security" => "max\-age=31536000; includeSubDomains"
    ]
.fi

.PP
Définition à la ligne \fB23\fP du fichier \fBResponse\&.php\fP\&.
.SS "\fBResponseCode\fP $responseCode = ResponseCode::OK\fC [protected]\fP"

.PP
Définition à la ligne \fB13\fP du fichier \fBResponse\&.php\fP\&.

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Sabo final à partir du code source\&.
