.TH "SaboCore\Cli\Theme" 3 "Mardi 23 Juillet 2024" "Version 1.1.1" "Sabo final" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SaboCore\Cli\Theme
.SH SYNOPSIS
.br
.PP
.SS "Énumérations"

.in +1c
.ti -1c
.RI "enum \fBTheme\fP : string { \fBIMPORTANT_ERROR_STYLE\fP = 'importantError' }"
.br
.RI "Configuration de thème d'affichage du cli\&. "
.in -1c
.SH "Documentation du type de l'énumération"
.PP 
.SS "enum \fBTheme\fP : string"

.PP
Configuration de thème d'affichage du cli\&. 
.PP
\fBAuteur\fP
.RS 4
yahaya bathily https://github.com/yahvya/ 
.RE
.PP

.PP
\fBValeurs énumérées\fP
.in +1c
.TP
\fB\fIIMPORTANT_ERROR_STYLE \fP\fP
Style de texte basique\&. Style de texte spécial
.PP
Style du texte non important
.PP
Style du texte titre important
.PP
Style du texte mis en avant
.PP
erreur basique
.PP
Erreur importante 
.PP
Définition à la ligne \fB9\fP du fichier \fBTheme\&.php\fP\&.
.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Sabo final à partir du code source\&.
