.TH "BladeMailProvider" 3 "Mardi 23 Juillet 2024" "Version 1.1.1" "Sabo final" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BladeMailProvider \- Fournisseur de mail template blade\&.  

.SH SYNOPSIS
.br
.PP
.PP
Est dérivée de \fBMailerTemplateProvider\fP\&.
.SS "Fonctions membres publiques"

.in +1c
.ti -1c
.RI "\fBbuildContent\fP ()"
.br
.in -1c

Fonctions membres publiques hérités de \fBMailerTemplateProvider\fP
.in +1c
.ti -1c
.RI "\fB__construct\fP (string $templatePath, string $altContent, array $templateDatas=[])"
.br
.ti -1c
.RI "\fBgetAltContent\fP ()"
.br
.ti -1c
.RI "\fBbuildContent\fP ()"
.br
.in -1c
.SS "Membres hérités additionnels"


Attributs protégés hérités de \fBMailerTemplateProvider\fP
.in +1c
.ti -1c
.RI "string \fB$templatePath\fP"
.br
.ti -1c
.RI "string \fB$altContent\fP"
.br
.ti -1c
.RI "array \fB$templateDatas\fP"
.br
.in -1c
.SH "Description détaillée"
.PP 
Fournisseur de mail template blade\&. 


.PP
\fBAuteur\fP
.RS 4
yahaya bathily https://github.com/yahvya 
.RE
.PP

.PP
Définition à la ligne \fB15\fP du fichier \fBBladeMailProvider\&.php\fP\&.
.SH "Documentation des fonctions membres"
.PP 
.SS "buildContent ()"

.PP
\fBRenvoie\fP
.RS 4
string le contenu du template construit 
.RE
.PP
\fBExceptions\fP
.RS 4
\fIThrowable\fP en cas d'erreur 
.RE
.PP

.PP
Réimplémentée à partir de \fBMailerTemplateProvider\fP\&.
.PP
Définition à la ligne \fB17\fP du fichier \fBBladeMailProvider\&.php\fP\&.

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Sabo final à partir du code source\&.
