.TH "LaunchServerCommand" 3 "Mardi 23 Juillet 2024" "Version 1.1.1" "Sabo final" \" -*- nroff -*-
.ad l
.nh
.SH NAME
LaunchServerCommand \- Commande de lancement de serveur\&.  

.SH SYNOPSIS
.br
.PP
.PP
Est dérivée de \fBSaboCommand\fP\&.
.SS "Fonctions membres publiques"

.in +1c
.ti -1c
.RI "\fBexecCommand\fP (\fBSaboCli\fP $cli)"
.br
.RI "Exécute la commande\&. "
.ti -1c
.RI "\fBgetHelpLines\fP ()"
.br
.in -1c

Fonctions membres publiques hérités de \fBSaboCommand\fP
.in +1c
.ti -1c
.RI "\fB__construct\fP (string $commandName)"
.br
.ti -1c
.RI "\fBgetName\fP ()"
.br
.ti -1c
.RI "\fBexecCommand\fP (\fBSaboCli\fP $cli)"
.br
.RI "Exécute la commande\&. "
.ti -1c
.RI "\fBgetHelpLines\fP ()"
.br
.in -1c
.SS "Fonctions membres publiques statiques"

.in +1c
.ti -1c
.RI "static \fBmanageSyncRequirements\fP (\fBSaboCli\fP $cli)"
.br
.RI "Vérifie si la commande de synchronisation est présente sinon tente de l'installer\&. "
.in -1c
.SS "Attributs protégés"

.in +1c
.ti -1c
.RI "const string \fBDEFAULT_PORT\fP = '8080'"
.br
.RI "Port par défaut\&. "
.ti -1c
.RI "const string \fBDEFAULT_HOST\fP = '127\&.0\&.0\&.1'"
.br
.RI "Hôte par défaut\&. "
.ti -1c
.RI "const string \fBFILES_SEPARATOR\fP = ','"
.br
.RI "Séparateur accepté sur les fichiers\&. "
.ti -1c
.RI "const array \fBDEFAULT_FILE_TYPES\fP = ['php','js','css','twig','blade']"
.br
.RI "Extensions de fichier par défaut écoutées\&. "
.ti -1c
.RI "const string \fBSYNC_COMMAND_NAME\fP = 'browser\-sync'"
.br
.RI "Commande de synchronisation\&. "
.in -1c

Attributs protégés hérités de \fBSaboCommand\fP
.in +1c
.ti -1c
.RI "string \fB$commandName\fP"
.br
.in -1c
.SS "Membres hérités additionnels"


Fonctions membres protégées hérités de \fBSaboCommand\fP
.in +1c
.ti -1c
.RI "\fBgetOptions\fP (\fBSaboCli\fP $cli, string \&.\&.\&. $optionNames)"
.br
.RI "Récupère les valeurs des options recherchées ou les demandes si non trouvées\&. "
.ti -1c
.RI "\fBask\fP (string $toAsk, \fBConfig\fP $themeConfig)"
.br
.RI "Pose une question\&. "
.in -1c
.SH "Description détaillée"
.PP 
Commande de lancement de serveur\&. 


.PP
\fBAuteur\fP
.RS 4
yahaya bathily https://github.com/yahvya 
.RE
.PP

.PP
Définition à la ligne \fB15\fP du fichier \fBLaunchServerCommand\&.php\fP\&.
.SH "Documentation des fonctions membres"
.PP 
.SS "execCommand (\fBSaboCli\fP $cli)"

.PP
Exécute la commande\&. 
.PP
\fBParamètres\fP
.RS 4
\fI$cli\fP le gestionnaire cli lié 
.RE
.PP
\fBExceptions\fP
.RS 4
\fIConfigException|Throwable\fP en cas d'erreur interne 
.RE
.PP
\fBRenvoie\fP
.RS 4
void 
.RE
.PP

.PP
Réimplémentée à partir de \fBSaboCommand\fP\&.
.PP
Définition à la ligne \fB42\fP du fichier \fBLaunchServerCommand\&.php\fP\&.
.SS "getHelpLines ()"

.PP
\fBRenvoie\fP
.RS 4
string[] les lignes à afficher pour l'aide de la commande 
.RE
.PP

.PP
Réimplémentée à partir de \fBSaboCommand\fP\&.
.PP
Définition à la ligne \fB119\fP du fichier \fBLaunchServerCommand\&.php\fP\&.
.SS "static manageSyncRequirements (\fBSaboCli\fP $cli)\fC [static]\fP"

.PP
Vérifie si la commande de synchronisation est présente sinon tente de l'installer\&. 
.PP
\fBParamètres\fP
.RS 4
\fI$cli\fP Cli 
.RE
.PP
\fBRenvoie\fP
.RS 4
bool si la commande est disponible d'utilisation 
.RE
.PP
\fBExceptions\fP
.RS 4
\fIConfigException\fP en cas d'erreur de configuration 
.RE
.PP

.PP
Définition à la ligne \fB137\fP du fichier \fBLaunchServerCommand\&.php\fP\&.
.SH "Documentation des champs"
.PP 
.SS "const array DEFAULT_FILE_TYPES = ['php','js','css','twig','blade']\fC [protected]\fP"

.PP
Extensions de fichier par défaut écoutées\&. 
.PP
Définition à la ligne \fB34\fP du fichier \fBLaunchServerCommand\&.php\fP\&.
.SS "const string DEFAULT_HOST = '127\&.0\&.0\&.1'\fC [protected]\fP"

.PP
Hôte par défaut\&. 
.PP
Définition à la ligne \fB24\fP du fichier \fBLaunchServerCommand\&.php\fP\&.
.SS "const string DEFAULT_PORT = '8080'\fC [protected]\fP"

.PP
Port par défaut\&. 
.PP
Définition à la ligne \fB19\fP du fichier \fBLaunchServerCommand\&.php\fP\&.
.SS "const string FILES_SEPARATOR = ','\fC [protected]\fP"

.PP
Séparateur accepté sur les fichiers\&. 
.PP
Définition à la ligne \fB29\fP du fichier \fBLaunchServerCommand\&.php\fP\&.
.SS "const string SYNC_COMMAND_NAME = 'browser\-sync'\fC [protected]\fP"

.PP
Commande de synchronisation\&. 
.PP
Définition à la ligne \fB39\fP du fichier \fBLaunchServerCommand\&.php\fP\&.

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Sabo final à partir du code source\&.
