.TH "Route" 3 "Mardi 23 Juillet 2024" "Version 1.1.1" "Sabo final" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Route \- Route de l'application\&.  

.SH SYNOPSIS
.br
.PP
.SS "Fonctions membres publiques"

.in +1c
.ti -1c
.RI "\fB__construct\fP (string $requestMethod, string $link, Closure|array $toExecute, string $routeName, array $genericParamsRegex=[], array $accessVerifiers=[])"
.br
.ti -1c
.RI "\fBaddPrefix\fP (string $prefix, array $genericParameters=[], array $accessVerifiers=[])"
.br
.RI "Ajoute un préfix au lien\&. "
.ti -1c
.RI "\fBmatchWith\fP (string $url)"
.br
.RI "Vérifie si la route match avec l'URL\&. "
.ti -1c
.RI "\fBgetToExecute\fP ()"
.br
.ti -1c
.RI "\fBgetAccessVerifiers\fP ()"
.br
.ti -1c
.RI "\fBgetRequestMethod\fP ()"
.br
.ti -1c
.RI "\fBgetRouteName\fP ()"
.br
.ti -1c
.RI "\fBgetRouteLink\fP ()"
.br
.in -1c
.SS "Fonctions membres publiques statiques"

.in +1c
.ti -1c
.RI "static \fBget\fP (string $link, Closure|array $toExecute, string $routeName, array $genericParamsRegex=[], array $accessVerifiers=[])"
.br
.RI "Crée une route get\&. "
.ti -1c
.RI "static \fBdelete\fP (string $link, Closure|array $toExecute, string $routeName, array $genericParamsRegex=[], array $accessVerifiers=[])"
.br
.RI "Crée une route DELETE\&. "
.ti -1c
.RI "static \fBpost\fP (string $link, Closure|array $toExecute, string $routeName, array $genericParamsRegex=[], array $accessVerifiers=[])"
.br
.RI "Crée une route POST\&. "
.ti -1c
.RI "static \fBput\fP (string $link, Closure|array $toExecute, string $routeName, array $genericParamsRegex=[], array $accessVerifiers=[])"
.br
.RI "Crée une route PUT\&. "
.ti -1c
.RI "static \fBpatch\fP (string $link, Closure|array $toExecute, string $routeName, array $genericParamsRegex=[], array $accessVerifiers=[])"
.br
.RI "Crée une route PATCH\&. "
.ti -1c
.RI "static \fBoptions\fP (string $link, Closure|array $toExecute, string $routeName, array $genericParamsRegex=[], array $accessVerifiers=[])"
.br
.RI "Crée une route OPTIONS\&. "
.ti -1c
.RI "static \fBhead\fP (string $link, Closure|array $toExecute, string $routeName, array $genericParamsRegex=[], array $accessVerifiers=[])"
.br
.RI "Crée une route HEAD\&. "
.ti -1c
.RI "static \fBtrace\fP (string $link, Closure|array $toExecute, string $routeName, array $genericParamsRegex=[], array $accessVerifiers=[])"
.br
.RI "Crée une route TRACE\&. "
.in -1c
.SS "Fonctions membres protégées"

.in +1c
.ti -1c
.RI "\fBupdateConfig\fP ()"
.br
.RI "Met à jour les données de la route à partir des informations contenues dans le lien ainsi que les paramètres génériques\&. "
.in -1c
.SS "Attributs protégés"

.in +1c
.ti -1c
.RI "string \fB$requestMethod\fP"
.br
.ti -1c
.RI "string \fB$link\fP"
.br
.ti -1c
.RI "string \fB$verificationRegex\fP"
.br
.ti -1c
.RI "string \fB$routeName\fP"
.br
.ti -1c
.RI "array \fB$genericParamsRegex\fP"
.br
.ti -1c
.RI "array \fB$genericParamsOrder\fP = []"
.br
.ti -1c
.RI "array \fB$accessVerifiers\fP"
.br
.ti -1c
.RI "Closure array \fB$toExecute\fP"
.br
.in -1c
.SH "Description détaillée"
.PP 
Route de l'application\&. 


.PP
\fBAuteur\fP
.RS 4
yahaya bathily https://github.com/yahvya 
.RE
.PP

.PP
Définition à la ligne \fB15\fP du fichier \fBRoute\&.php\fP\&.
.SH "Documentation des constructeurs et destructeur"
.PP 
.SS "__construct (string $requestMethod, string $link, Closure|array $toExecute, string $routeName, array $genericParamsRegex = \fC[]\fP, array $accessVerifiers = \fC[]\fP)"

.PP
\fBParamètres\fP
.RS 4
\fI$requestMethod\fP méthode de requête (get, post, \&.\&.\&.) 
.br
\fI$link\fP lien 
.br
\fI$toExecute\fP à exécuter pour traiter la route 
.br
\fI$routeName\fP nom de la route 
.br
\fI$genericParamsRegex\fP expressions régulières associées aux paramètres génériques 
.br
\fI$accessVerifiers\fP vérificateurs d'accès à la route, seuls les fonctions failures sont prises en compte et retournent Response 
.RE
.PP

.PP
Définition à la ligne \fB64\fP du fichier \fBRoute\&.php\fP\&.
.SH "Documentation des fonctions membres"
.PP 
.SS "addPrefix (string $prefix, array $genericParameters = \fC[]\fP, array $accessVerifiers = \fC[]\fP)"

.PP
Ajoute un préfix au lien\&. 
.PP
\fBParamètres\fP
.RS 4
\fI$prefix\fP préfixe à ajouter à la route 
.br
\fI$genericParameters\fP paramètres génériques à ajouter à la route 
.br
\fI$accessVerifiers\fP vérificateurs d'accès à la route, seuls les fonctions failures sont prises en compte et retournent Response 
.RE
.PP
\fBRenvoie\fP
.RS 4
$this 
.RE
.PP

.PP
Définition à la ligne \fB86\fP du fichier \fBRoute\&.php\fP\&.
.SS "static delete (string $link, Closure|array $toExecute, string $routeName, array $genericParamsRegex = \fC[]\fP, array $accessVerifiers = \fC[]\fP)\fC [static]\fP"

.PP
Crée une route DELETE\&. 
.PP
\fBParamètres\fP
.RS 4
\fI$link\fP Lien de la route 
.br
\fI$toExecute\fP Fonction à exécuter pour traiter la route 
.br
\fI$routeName\fP Nom de la route 
.br
\fI$genericParamsRegex\fP Expressions régulières associées aux paramètres génériques 
.br
\fI$accessVerifiers\fP Vérificateurs d'accès à la route, seuls les fonctions failures sont prises en compte et retournent Response 
.RE
.PP
\fBRenvoie\fP
.RS 4
Route La route créée 
.RE
.PP

.PP
Définition à la ligne \fB219\fP du fichier \fBRoute\&.php\fP\&.
.SS "static get (string $link, Closure|array $toExecute, string $routeName, array $genericParamsRegex = \fC[]\fP, array $accessVerifiers = \fC[]\fP)\fC [static]\fP"

.PP
Crée une route get\&. 
.PP
\fBParamètres\fP
.RS 4
\fI$link\fP lien 
.br
\fI$toExecute\fP à exécuter pour traiter la route 
.br
\fI$routeName\fP nom de la route 
.br
\fI$genericParamsRegex\fP expressions régulières associées aux paramètres génériques 
.br
\fI$accessVerifiers\fP vérificateurs d'accès à la route, seuls les fonctions failures sont prises en compte et retournent Response 
.RE
.PP
\fBRenvoie\fP
.RS 4
Route la route crée 
.RE
.PP

.PP
Définition à la ligne \fB199\fP du fichier \fBRoute\&.php\fP\&.
.SS "getAccessVerifiers ()"

.PP
\fBRenvoie\fP
.RS 4
Verifier[] les vérificateurs de la route 
.RE
.PP

.PP
Définition à la ligne \fB131\fP du fichier \fBRoute\&.php\fP\&.
.SS "getRequestMethod ()"

.PP
\fBRenvoie\fP
.RS 4
string la méthode de requête 
.RE
.PP

.PP
Définition à la ligne \fB138\fP du fichier \fBRoute\&.php\fP\&.
.SS "getRouteLink ()"

.PP
\fBRenvoie\fP
.RS 4
string le lien associé 
.RE
.PP

.PP
Définition à la ligne \fB152\fP du fichier \fBRoute\&.php\fP\&.
.SS "getRouteName ()"

.PP
\fBRenvoie\fP
.RS 4
string le nom de la route 
.RE
.PP

.PP
Définition à la ligne \fB145\fP du fichier \fBRoute\&.php\fP\&.
.SS "getToExecute ()"

.PP
\fBRenvoie\fP
.RS 4
Closure|array l'action d'exécution 
.RE
.PP

.PP
Définition à la ligne \fB124\fP du fichier \fBRoute\&.php\fP\&.
.SS "static head (string $link, Closure|array $toExecute, string $routeName, array $genericParamsRegex = \fC[]\fP, array $accessVerifiers = \fC[]\fP)\fC [static]\fP"

.PP
Crée une route HEAD\&. 
.PP
\fBParamètres\fP
.RS 4
\fI$link\fP Lien de la route 
.br
\fI$toExecute\fP Fonction à exécuter pour traiter la route 
.br
\fI$routeName\fP Nom de la route 
.br
\fI$genericParamsRegex\fP Expressions régulières associées aux paramètres génériques 
.br
\fI$accessVerifiers\fP Vérificateurs d'accès à la route, seuls les fonctions failures sont prises en compte et retournent Response 
.RE
.PP
\fBRenvoie\fP
.RS 4
Route La route créée 
.RE
.PP

.PP
Définition à la ligne \fB319\fP du fichier \fBRoute\&.php\fP\&.
.SS "matchWith (string $url)"

.PP
Vérifie si la route match avec l'URL\&. 
.PP
\fBParamètres\fP
.RS 4
\fI$url\fP l'URL 
.RE
.PP
\fBRenvoie\fP
.RS 4
MatchResult le résultat du match contenant l'association si match 
.RE
.PP

.PP
Définition à la ligne \fB104\fP du fichier \fBRoute\&.php\fP\&.
.SS "static options (string $link, Closure|array $toExecute, string $routeName, array $genericParamsRegex = \fC[]\fP, array $accessVerifiers = \fC[]\fP)\fC [static]\fP"

.PP
Crée une route OPTIONS\&. 
.PP
\fBParamètres\fP
.RS 4
\fI$link\fP Lien de la route 
.br
\fI$toExecute\fP Fonction à exécuter pour traiter la route 
.br
\fI$routeName\fP Nom de la route 
.br
\fI$genericParamsRegex\fP Expressions régulières associées aux paramètres génériques 
.br
\fI$accessVerifiers\fP Vérificateurs d'accès à la route, seuls les fonctions failures sont prises en compte et retournent Response 
.RE
.PP
\fBRenvoie\fP
.RS 4
Route La route créée 
.RE
.PP

.PP
Définition à la ligne \fB299\fP du fichier \fBRoute\&.php\fP\&.
.SS "static patch (string $link, Closure|array $toExecute, string $routeName, array $genericParamsRegex = \fC[]\fP, array $accessVerifiers = \fC[]\fP)\fC [static]\fP"

.PP
Crée une route PATCH\&. 
.PP
\fBParamètres\fP
.RS 4
\fI$link\fP Lien de la route 
.br
\fI$toExecute\fP Fonction à exécuter pour traiter la route 
.br
\fI$routeName\fP Nom de la route 
.br
\fI$genericParamsRegex\fP Expressions régulières associées aux paramètres génériques 
.br
\fI$accessVerifiers\fP Vérificateurs d'accès à la route, seuls les fonctions failures sont prises en compte et retournent Response 
.RE
.PP
\fBRenvoie\fP
.RS 4
Route La route créée 
.RE
.PP

.PP
Définition à la ligne \fB279\fP du fichier \fBRoute\&.php\fP\&.
.SS "static post (string $link, Closure|array $toExecute, string $routeName, array $genericParamsRegex = \fC[]\fP, array $accessVerifiers = \fC[]\fP)\fC [static]\fP"

.PP
Crée une route POST\&. 
.PP
\fBParamètres\fP
.RS 4
\fI$link\fP Lien de la route 
.br
\fI$toExecute\fP Fonction à exécuter pour traiter la route 
.br
\fI$routeName\fP Nom de la route 
.br
\fI$genericParamsRegex\fP Expressions régulières associées aux paramètres génériques 
.br
\fI$accessVerifiers\fP Vérificateurs d'accès à la route, seuls les fonctions failures sont prises en compte et retournent Response 
.RE
.PP
\fBRenvoie\fP
.RS 4
Route La route créée 
.RE
.PP

.PP
Définition à la ligne \fB239\fP du fichier \fBRoute\&.php\fP\&.
.SS "static put (string $link, Closure|array $toExecute, string $routeName, array $genericParamsRegex = \fC[]\fP, array $accessVerifiers = \fC[]\fP)\fC [static]\fP"

.PP
Crée une route PUT\&. 
.PP
\fBParamètres\fP
.RS 4
\fI$link\fP Lien de la route 
.br
\fI$toExecute\fP Fonction à exécuter pour traiter la route 
.br
\fI$routeName\fP Nom de la route 
.br
\fI$genericParamsRegex\fP Expressions régulières associées aux paramètres génériques 
.br
\fI$accessVerifiers\fP Vérificateurs d'accès à la route, seuls les fonctions failures sont prises en compte et retournent Response 
.RE
.PP
\fBRenvoie\fP
.RS 4
Route La route créée 
.RE
.PP

.PP
Définition à la ligne \fB259\fP du fichier \fBRoute\&.php\fP\&.
.SS "static trace (string $link, Closure|array $toExecute, string $routeName, array $genericParamsRegex = \fC[]\fP, array $accessVerifiers = \fC[]\fP)\fC [static]\fP"

.PP
Crée une route TRACE\&. 
.PP
\fBParamètres\fP
.RS 4
\fI$link\fP Lien de la route 
.br
\fI$toExecute\fP Fonction à exécuter pour traiter la route 
.br
\fI$routeName\fP Nom de la route 
.br
\fI$genericParamsRegex\fP Expressions régulières associées aux paramètres génériques 
.br
\fI$accessVerifiers\fP Vérificateurs d'accès à la route, seuls les fonctions failures sont prises en compte et retournent Response 
.RE
.PP
\fBRenvoie\fP
.RS 4
Route La route créée 
.RE
.PP

.PP
Définition à la ligne \fB339\fP du fichier \fBRoute\&.php\fP\&.
.SS "updateConfig ()\fC [protected]\fP"

.PP
Met à jour les données de la route à partir des informations contenues dans le lien ainsi que les paramètres génériques\&. 
.PP
\fBRenvoie\fP
.RS 4
$this 
.RE
.PP

.PP
Définition à la ligne \fB160\fP du fichier \fBRoute\&.php\fP\&.
.SH "Documentation des champs"
.PP 
.SS "array $accessVerifiers\fC [protected]\fP"

.PP
Définition à la ligne \fB49\fP du fichier \fBRoute\&.php\fP\&.
.SS "array $genericParamsOrder = []\fC [protected]\fP"

.PP
Définition à la ligne \fB44\fP du fichier \fBRoute\&.php\fP\&.
.SS "array $genericParamsRegex\fC [protected]\fP"

.PP
Définition à la ligne \fB39\fP du fichier \fBRoute\&.php\fP\&.
.SS "string $link\fC [protected]\fP"

.PP
Définition à la ligne \fB24\fP du fichier \fBRoute\&.php\fP\&.
.SS "string $requestMethod\fC [protected]\fP"

.PP
Définition à la ligne \fB19\fP du fichier \fBRoute\&.php\fP\&.
.SS "string $routeName\fC [protected]\fP"

.PP
Définition à la ligne \fB34\fP du fichier \fBRoute\&.php\fP\&.
.SS "Closure array $toExecute\fC [protected]\fP"

.PP
Définition à la ligne \fB54\fP du fichier \fBRoute\&.php\fP\&.
.SS "string $verificationRegex\fC [protected]\fP"

.PP
Définition à la ligne \fB29\fP du fichier \fBRoute\&.php\fP\&.

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Sabo final à partir du code source\&.
