.TH "SaboCore\Database\Default\Attributes" 3 "Mardi 23 Juillet 2024" "Version 1.1.1" "Sabo final" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SaboCore\Database\Default\Attributes
.SH SYNOPSIS
.br
.PP
.SS "Structures de données"

.in +1c
.ti -1c
.RI "class \fBBinaryColumn\fP"
.br
.RI "Champs de type binary\&. "
.ti -1c
.RI "class \fBBoolColumn\fP"
.br
.RI "Champs de type Booléen\&. "
.ti -1c
.RI "class \fBCharColumn\fP"
.br
.RI "Champs de type char\&. "
.ti -1c
.RI "class \fBDecimalColumn\fP"
.br
.RI "Champs de type decimal\&. "
.ti -1c
.RI "class \fBEnumColumn\fP"
.br
.RI "Champs de type énumération\&. "
.ti -1c
.RI "class \fBIntColumn\fP"
.br
.RI "Champs de type int\&. "
.ti -1c
.RI "class \fBJoinedColumn\fP"
.br
.RI "Attribut de liaison de tables\&. "
.ti -1c
.RI "class \fBJsonColumn\fP"
.br
.RI "Champs de type json\&. "
.ti -1c
.RI "class \fBSqlAttribute\fP"
.br
.RI "Représente un attribut pouvant être créé en sql\&. "
.ti -1c
.RI "class \fBTableColumn\fP"
.br
.RI "Représentation d'une colonne\&. "
.ti -1c
.RI "class \fBTableName\fP"
.br
.ti -1c
.RI "class \fBTextColumn\fP"
.br
.RI "Champs de type text\&. "
.ti -1c
.RI "class \fBTimestampColumn\fP"
.br
.RI "Champs de type timestamp|date|time\&. "
.ti -1c
.RI "class \fBTinyIntColumn\fP"
.br
.RI "Champs de type tinyint\&. "
.ti -1c
.RI "class \fBVarBinaryColumn\fP"
.br
.RI "Champs de type binary à taille variable\&. "
.ti -1c
.RI "class \fBVarcharColumn\fP"
.br
.RI "Champs de type varchar\&. "
.in -1c
.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Sabo final à partir du code source\&.
