.TH "MysqlQueryBuilder" 3 "Mardi 23 Juillet 2024" "Version 1.1.1" "Sabo final" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MysqlQueryBuilder \- Constructeur de requête\&.  

.SH SYNOPSIS
.br
.PP
.SS "Fonctions membres publiques"

.in +1c
.ti -1c
.RI "\fB__construct\fP (\fBMysqlModel\fP $model)"
.br
.ti -1c
.RI "\fBreset\fP ()"
.br
.RI "Remet à 0 le contenu du QueryBuilder\&. "
.ti -1c
.RI "\fBprepareRequest\fP (PDO $pdo)"
.br
.RI "Prépare la requête\&. "
.ti -1c
.RI "\fBas\fP (string $alias)"
.br
.RI "Met à jour l'alias de la table\&. "
.ti -1c
.RI "\fBgetRealSql\fP ()"
.br
.ti -1c
.RI "\fBgetSql\fP ()"
.br
.ti -1c
.RI "\fBgetBaseModel\fP ()"
.br
.ti -1c
.RI "\fBgetBindValues\fP ()"
.br
.ti -1c
.RI "\fBjoinBuilder\fP (\fBMysqlQueryBuilder\fP $toJoin,?string $sqlBefore=null,?string $sqlAfter=null)"
.br
.RI "Join la requête fournie dans la requête actuelle\&. "
.ti -1c
.RI "\fBstaticRequest\fP (string $sqlString, array $toBind=[], bool $justConcat=false)"
.br
.RI "Fonctions de requêtes\&. "
.ti -1c
.RI "\fBselect\fP (string|\fBMysqlFunction\fP \&.\&.\&. $toSelect)"
.br
.RI "Ajoute la chaine SELECT [] FROM table\&. "
.ti -1c
.RI "\fBinsert\fP (array $insertConfig)"
.br
.RI "Ajoute la chaine INSERT INTO\&. "
.ti -1c
.RI "\fBupdate\fP (array $updateConfig)"
.br
.RI "Ajoute la chaine UPDATE table SET []\&. "
.ti -1c
.RI "\fBdelete\fP ()"
.br
.RI "Ajoute la chaine DELETE FROM table\&. "
.ti -1c
.RI "\fBwhere\fP ()"
.br
.RI "Ajoute la chaine WHERE\&. "
.ti -1c
.RI "\fBcond\fP (\fBMysqlCondition\fP|\fBMysqlCondSeparator\fP \&.\&.\&. $conditions)"
.br
.RI "Ajoute les conditions where\&. "
.ti -1c
.RI "\fBhaving\fP (\fBMysqlCondition\fP|\fBMysqlCondSeparator\fP \&.\&.\&. $conditions)"
.br
.RI "Ajoute la chaine HAVING \&.\&.\&. "
.ti -1c
.RI "\fBorderBy\fP (array \&.\&.\&. $configs)"
.br
.RI "Ajoute la chaine ORDER BY \&.\&.\&. ($builder->orderBy(['price','ASC'],['id','DESC'] ) ) "
.ti -1c
.RI "\fBgroupBy\fP (string \&.\&.\&. $attributesNames)"
.br
.RI "Ajoute la chaine GROUP BY\&. "
.ti -1c
.RI "\fBlimit\fP (int $count,?int $offset=null)"
.br
.RI "Ajoute la clause limit\&. "
.in -1c
.SS "Fonctions membres publiques statiques"

.in +1c
.ti -1c
.RI "static \fBcreateFrom\fP (string $modelClass)"
.br
.RI "Crée un query builder à partir du model fourni\&. "
.in -1c
.SS "Fonctions membres protégées"

.in +1c
.ti -1c
.RI "\fBmanageValueDatas\fP (\fBTableColumn\fP $columnConfig, mixed $data,?string $sqlBefore=null,?string $sqlAfter=null)"
.br
.RI "Récupère les valeurs à bind en fonction de la valeur et fourni la chaine sql résultante\&. "
.ti -1c
.RI "\fBreplaceAttributesNameIn\fP (string $string)"
.br
.RI "Remplace le nom des attributs par le nom de colonne associé "
.ti -1c
.RI "\fBparseCondition\fP (\fBMysqlCondition\fP $condition)"
.br
.RI "Parse les données de la condition\&. "
.ti -1c
.RI "\fBparseConditionSequence\fP (array $sequence)"
.br
.RI "Parse une séquence de conditions et de séparateurs\&. "
.in -1c
.SS "Attributs protégés"

.in +1c
.ti -1c
.RI "string \fB$sqlString\fP"
.br
.ti -1c
.RI "array \fB$toBind\fP"
.br
.ti -1c
.RI "\fBMysqlModel\fP \fB$baseModel\fP"
.br
.ti -1c
.RI "string \fB$tableAlias\fP"
.br
.in -1c
.SH "Description détaillée"
.PP 
Constructeur de requête\&. 


.PP
\fBAuteur\fP
.RS 4
yahaya bathily https://github.com/yahvya 
.RE
.PP

.PP
Définition à la ligne \fB21\fP du fichier \fBMysqlQueryBuilder\&.php\fP\&.
.SH "Documentation des constructeurs et destructeur"
.PP 
.SS "__construct (\fBMysqlModel\fP $model)"

.PP
\fBParamètres\fP
.RS 4
\fI$model\fP instance du model 
.RE
.PP

.PP
Définition à la ligne \fB45\fP du fichier \fBMysqlQueryBuilder\&.php\fP\&.
.SH "Documentation des fonctions membres"
.PP 
.SS "as (string $alias)"

.PP
Met à jour l'alias de la table\&. 
.PP
\fBParamètres\fP
.RS 4
\fI$alias\fP nouvel alias 
.RE
.PP
\fBRenvoie\fP
.RS 4
$this 
.RE
.PP

.PP
Définition à la ligne \fB107\fP du fichier \fBMysqlQueryBuilder\&.php\fP\&.
.SS "cond (\fBMysqlCondition\fP|\fBMysqlCondSeparator\fP \&.\&.\&. $conditions)"

.PP
Ajoute les conditions where\&. 
.PP
\fBParamètres\fP
.RS 4
\fIMysqlCondition|MysqlCondSeparator\fP \&.\&.\&.$conditions conditions de vérification 
.RE
.PP
\fBRenvoie\fP
.RS 4
$this 
.RE
.PP

.PP
Définition à la ligne \fB437\fP du fichier \fBMysqlQueryBuilder\&.php\fP\&.
.SS "static createFrom (string $modelClass)\fC [static]\fP"

.PP
Crée un query builder à partir du model fourni\&. 
.PP
\fBParamètres\fP
.RS 4
\fI$modelClass\fP model de la class 
.RE
.PP
\fBRenvoie\fP
.RS 4
MysqlQueryBuilder l'instance crée 
.RE
.PP
\fBExceptions\fP
.RS 4
\fIConfigException\fP en cas d'erreur de configuration 
.RE
.PP

.PP
Définition à la ligne \fB56\fP du fichier \fBMysqlQueryBuilder\&.php\fP\&.
.SS "delete ()"

.PP
Ajoute la chaine DELETE FROM table\&. 
.PP
\fBRenvoie\fP
.RS 4
$this 
.RE
.PP

.PP
Définition à la ligne \fB416\fP du fichier \fBMysqlQueryBuilder\&.php\fP\&.
.SS "getBaseModel ()"

.PP
\fBRenvoie\fP
.RS 4
MysqlModel instance du model de base 
.RE
.PP

.PP
Définition à la ligne \fB135\fP du fichier \fBMysqlQueryBuilder\&.php\fP\&.
.SS "getBindValues ()"

.PP
\fBRenvoie\fP
.RS 4
MysqlBindDatas[] les valeurs à bind 
.RE
.PP

.PP
Définition à la ligne \fB142\fP du fichier \fBMysqlQueryBuilder\&.php\fP\&.
.SS "getRealSql ()"

.PP
\fBRenvoie\fP
.RS 4
string La chaine sql sans modification 
.RE
.PP
\fBAttention\fP
.RS 4
La chaine fournie peut ne pas être utilisable 
.RE
.PP

.PP
Définition à la ligne \fB117\fP du fichier \fBMysqlQueryBuilder\&.php\fP\&.
.SS "getSql ()"

.PP
\fBRenvoie\fP
.RS 4
string La chaine sql formaté pour une requête 
.RE
.PP

.PP
Définition à la ligne \fB124\fP du fichier \fBMysqlQueryBuilder\&.php\fP\&.
.SS "groupBy (string \&.\&.\&. $attributesNames)"

.PP
Ajoute la chaine GROUP BY\&. 
.PP
\fBParamètres\fP
.RS 4
\fIstring\fP \&.\&.\&.$attributesNames nom des attributs 
.RE
.PP
\fBRenvoie\fP
.RS 4
$this 
.RE
.PP

.PP
Définition à la ligne \fB485\fP du fichier \fBMysqlQueryBuilder\&.php\fP\&.
.SS "having (\fBMysqlCondition\fP|\fBMysqlCondSeparator\fP \&.\&.\&. $conditions)"

.PP
Ajoute la chaine HAVING \&.\&.\&. 
.PP
\fBParamètres\fP
.RS 4
\fIMysqlCondition|MysqlCondSeparator\fP \&.\&.\&.$conditions conditions de vérification 
.RE
.PP
\fBRenvoie\fP
.RS 4
$this 
.RE
.PP

.PP
Définition à la ligne \fB451\fP du fichier \fBMysqlQueryBuilder\&.php\fP\&.
.SS "insert (array $insertConfig)"

.PP
Ajoute la chaine INSERT INTO\&. 
.PP
\fBParamètres\fP
.RS 4
\fI$insertConfig\fP Tableau indicé par le nom des attributs à changer et avec valeur associé valeur|MysqlFunction|MysqlQueryBuilder 
.RE
.PP
\fBRenvoie\fP
.RS 4
$this 
.RE
.PP
\fBAttention\fP
.RS 4
en cas de fonction ne pas y placer d'alias 
.RE
.PP

.PP
Définition à la ligne \fB352\fP du fichier \fBMysqlQueryBuilder\&.php\fP\&.
.SS "joinBuilder (\fBMysqlQueryBuilder\fP $toJoin, ?string $sqlBefore = \fCnull\fP, ?string $sqlAfter = \fCnull\fP)"

.PP
Join la requête fournie dans la requête actuelle\&. 
.PP
\fBParamètres\fP
.RS 4
\fI$toJoin\fP Builder à joindre 
.br
\fI$sqlBefore\fP Chaine sql à placer à avant ou null 
.br
\fI$sqlAfter\fP Chaine sql à placer après ou null 
.RE
.PP
\fBRenvoie\fP
.RS 4
$this 
.RE
.PP

.PP
Définition à la ligne \fB153\fP du fichier \fBMysqlQueryBuilder\&.php\fP\&.
.SS "limit (int $count, ?int $offset = \fCnull\fP)"

.PP
Ajoute la clause limit\&. 
.PP
\fBParamètres\fP
.RS 4
\fI$count\fP Nombre d'éléments 
.br
\fI$offset\fP Offset 
.RE
.PP
\fBRenvoie\fP
.RS 4
$this 
.RE
.PP

.PP
Définition à la ligne \fB503\fP du fichier \fBMysqlQueryBuilder\&.php\fP\&.
.SS "manageValueDatas (\fBTableColumn\fP $columnConfig, mixed $data, ?string $sqlBefore = \fCnull\fP, ?string $sqlAfter = \fCnull\fP)\fC [protected]\fP"

.PP
Récupère les valeurs à bind en fonction de la valeur et fourni la chaine sql résultante\&. 
.PP
\fBAttention\fP
.RS 4
Ne modifie pas la chaine sql 
.RE
.PP
\fBParamètres\fP
.RS 4
\fI$columnConfig\fP Configuration de la colonne traitée 
.br
\fI$data\fP le type de donnée à traiter 
.br
\fI$sqlBefore\fP Chaine sql à placer avant en cas de Builder 
.br
\fI$sqlAfter\fP Chaine sql à placer après en cas de Builder 
.RE
.PP
\fBRenvoie\fP
.RS 4
array les données au format ['sql' => \&.\&.\&.,'toBind' => [MysqlBindDatas, \&.\&.\&.] 
.RE
.PP

.PP
Définition à la ligne \fB169\fP du fichier \fBMysqlQueryBuilder\&.php\fP\&.
.SS "orderBy (array \&.\&.\&. $configs)"

.PP
Ajoute la chaine ORDER BY \&.\&.\&. ($builder->orderBy(['price','ASC'],['id','DESC'] ) ) 
.PP
\fBParamètres\fP
.RS 4
\fIarray\fP \&.\&.\&.$configs Tableaux de deux éléments contenant en premier le nom de l'attribut suivi de 'ASC' ou 'DESC' 
.RE
.PP
\fBRenvoie\fP
.RS 4
$this 
.RE
.PP

.PP
Définition à la ligne \fB465\fP du fichier \fBMysqlQueryBuilder\&.php\fP\&.
.SS "parseCondition (\fBMysqlCondition\fP $condition)\fC [protected]\fP"

.PP
Parse les données de la condition\&. 
.PP
\fBParamètres\fP
.RS 4
\fI$condition\fP condition 
.RE
.PP
\fBRenvoie\fP
.RS 4
array les données de la condition ['sql' => \&.\&.\&.,'toBind' => MysqlBindDatas] 
.RE
.PP

.PP
Définition à la ligne \fB224\fP du fichier \fBMysqlQueryBuilder\&.php\fP\&.
.SS "parseConditionSequence (array $sequence)\fC [protected]\fP"

.PP
Parse une séquence de conditions et de séparateurs\&. 
.PP
\fBParamètres\fP
.RS 4
\fI(MysqlCondition|MysqlCondSeparator)[]\fP $sequence séquence 
.RE
.PP
\fBRenvoie\fP
.RS 4
array les données de la séquence ['sql' => \&.\&.\&.,'toBind' => [MysqlBindDatas, \&.\&.\&.]] 
.RE
.PP

.PP
Définition à la ligne \fB262\fP du fichier \fBMysqlQueryBuilder\&.php\fP\&.
.SS "prepareRequest (PDO $pdo)"

.PP
Prépare la requête\&. 
.PP
\fBParamètres\fP
.RS 4
\fI$pdo\fP instance pdo 
.RE
.PP
\fBRenvoie\fP
.RS 4
PDOStatement|null Résultat de la préparation 
.RE
.PP

.PP
Définition à la ligne \fB77\fP du fichier \fBMysqlQueryBuilder\&.php\fP\&.
.SS "replaceAttributesNameIn (string $string)\fC [protected]\fP"

.PP
Remplace le nom des attributs par le nom de colonne associé 
.PP
\fBParamètres\fP
.RS 4
\fI$string\fP chaine à traiter 
.RE
.PP
\fBRenvoie\fP
.RS 4
string résultat 
.RE
.PP
\fBAttention\fP
.RS 4
Le nom d'un attribut doit être placé entre {} 
.RE
.PP

.PP
Définition à la ligne \fB209\fP du fichier \fBMysqlQueryBuilder\&.php\fP\&.
.SS "reset ()"

.PP
Remet à 0 le contenu du QueryBuilder\&. 
.PP
\fBRenvoie\fP
.RS 4
$this 
.RE
.PP

.PP
Définition à la ligne \fB64\fP du fichier \fBMysqlQueryBuilder\&.php\fP\&.
.SS "select (string|\fBMysqlFunction\fP \&.\&.\&. $toSelect)"

.PP
Ajoute la chaine SELECT [] FROM table\&. 
.PP
\fBParamètres\fP
.RS 4
\fIstring|MysqlFunction\fP \&.\&.\&.$toSelect 
.RE
.PP
\fBRenvoie\fP
.RS 4
$this 
.RE
.PP
\fBAttention\fP
.RS 4
en fonction des champs sélectionnés le / les models générés seront partiellement construit s'il manque des champs\&. 
.RE
.PP

.PP
Définition à la ligne \fB316\fP du fichier \fBMysqlQueryBuilder\&.php\fP\&.
.SS "staticRequest (string $sqlString, array $toBind = \fC[]\fP, bool $justConcat = \fCfalse\fP)"

.PP
Fonctions de requêtes\&. Démarre une requête statique 
.PP
\fBParamètres\fP
.RS 4
\fI$sqlString\fP requête sql 
.br
\fI$toBind\fP Valeur à bind 
.br
\fI$justConcat\fP Si true concatène sinon remplace 
.RE
.PP
\fBRenvoie\fP
.RS 4
$this 
.RE
.PP

.PP
Définition à la ligne \fB297\fP du fichier \fBMysqlQueryBuilder\&.php\fP\&.
.SS "update (array $updateConfig)"

.PP
Ajoute la chaine UPDATE table SET []\&. 
.PP
\fBParamètres\fP
.RS 4
\fI$updateConfig\fP Tableau indicé par le nom des attributs à changer et avec valeur associé valeur|MysqlFunction|MysqlQueryBuilder 
.RE
.PP
\fBRenvoie\fP
.RS 4
$this 
.RE
.PP
\fBAttention\fP
.RS 4
en cas de fonction ne pas y placer d'alias 
.RE
.PP

.PP
Définition à la ligne \fB385\fP du fichier \fBMysqlQueryBuilder\&.php\fP\&.
.SS "where ()"

.PP
Ajoute la chaine WHERE\&. 
.PP
\fBRenvoie\fP
.RS 4
$this 
.RE
.PP

.PP
Définition à la ligne \fB426\fP du fichier \fBMysqlQueryBuilder\&.php\fP\&.
.SH "Documentation des champs"
.PP 
.SS "\fBMysqlModel\fP $baseModel\fC [protected]\fP"

.PP
Définition à la ligne \fB35\fP du fichier \fBMysqlQueryBuilder\&.php\fP\&.
.SS "string $sqlString\fC [protected]\fP"

.PP
Définition à la ligne \fB25\fP du fichier \fBMysqlQueryBuilder\&.php\fP\&.
.SS "string $tableAlias\fC [protected]\fP"

.PP
Définition à la ligne \fB40\fP du fichier \fBMysqlQueryBuilder\&.php\fP\&.
.SS "array $toBind\fC [protected]\fP"

.PP
Définition à la ligne \fB30\fP du fichier \fBMysqlQueryBuilder\&.php\fP\&.

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Sabo final à partir du code source\&.
