.TH "ResourceManager" 3 "Mardi 23 Juillet 2024" "Version 1.1.1" "Sabo final" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ResourceManager \- Gestinonaire de ressource\&.  

.SH SYNOPSIS
.br
.PP
.SS "Fonctions membres publiques"

.in +1c
.ti -1c
.RI "\fBsetRessource\fP (string|int $key, mixed $resource)"
.br
.RI "Stock une ressource\&. "
.ti -1c
.RI "\fBgetResource\fP (string|int $key)"
.br
.RI "Fourni une ressource\&. "
.ti -1c
.RI "\fBclear\fP ()"
.br
.RI "Vide les ressources\&. "
.in -1c
.SS "Attributs protégés"

.in +1c
.ti -1c
.RI "array \fB$resources\fP = []"
.br
.in -1c
.SH "Description détaillée"
.PP 
Gestinonaire de ressource\&. 


.PP
\fBAuteur\fP
.RS 4
yahaya bathily https://github.com/yahvya 
.RE
.PP

.PP
Définition à la ligne \fB9\fP du fichier \fBResourceManager\&.php\fP\&.
.SH "Documentation des fonctions membres"
.PP 
.SS "clear ()"

.PP
Vide les ressources\&. 
.PP
\fBRenvoie\fP
.RS 4
$this 
.RE
.PP

.PP
Définition à la ligne \fB40\fP du fichier \fBResourceManager\&.php\fP\&.
.SS "getResource (string|int $key)"

.PP
Fourni une ressource\&. 
.PP
\fBParamètres\fP
.RS 4
\fI$key\fP clé de mappage de la ressource 
.RE
.PP
\fBRenvoie\fP
.RS 4
mixed la ressource ou null 
.RE
.PP

.PP
Définition à la ligne \fB32\fP du fichier \fBResourceManager\&.php\fP\&.
.SS "setRessource (string|int $key, mixed $resource)"

.PP
Stock une ressource\&. 
.PP
\fBParamètres\fP
.RS 4
\fI$key\fP clé de mappage de la ressource 
.br
\fI$ressource\fP la ressource 
.RE
.PP
\fBRenvoie\fP
.RS 4
$this 
.RE
.PP

.PP
Définition à la ligne \fB21\fP du fichier \fBResourceManager\&.php\fP\&.
.SH "Documentation des champs"
.PP 
.SS "array $resources = []\fC [protected]\fP"

.PP
Définition à la ligne \fB13\fP du fichier \fBResourceManager\&.php\fP\&.

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Sabo final à partir du code source\&.
