.TH "DatabaseCondition" 3 "Mardi 23 Juillet 2024" "Version 1.1.1" "Sabo final" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DatabaseCondition \- Condition de récupération\&.  

.SH SYNOPSIS
.br
.PP
.PP
Dérivée par \fBMysqlCondition\fP\&.
.SS "Fonctions membres publiques"

.in +1c
.ti -1c
.RI "\fB__construct\fP (mixed $condGetter, \fBDatabaseComparator\fP $comparator, mixed $conditionValue)"
.br
.ti -1c
.RI "\fBgetCondGetter\fP ()"
.br
.ti -1c
.RI "\fBgetConditionValue\fP ()"
.br
.ti -1c
.RI "\fBgetComparator\fP ()"
.br
.in -1c
.SS "Attributs protégés"

.in +1c
.ti -1c
.RI "mixed \fB$condGetter\fP"
.br
.ti -1c
.RI "mixed \fB$conditionValue\fP"
.br
.ti -1c
.RI "\fBDatabaseComparator\fP \fB$comparator\fP"
.br
.in -1c
.SH "Description détaillée"
.PP 
Condition de récupération\&. 


.PP
\fBAuteur\fP
.RS 4
yahaya bathily https://github.com/yahvya 
.RE
.PP

.PP
Définition à la ligne \fB9\fP du fichier \fBDatabaseCondition\&.php\fP\&.
.SH "Documentation des constructeurs et destructeur"
.PP 
.SS "__construct (mixed $condGetter, \fBDatabaseComparator\fP $comparator, mixed $conditionValue)"

.PP
\fBParamètres\fP
.RS 4
\fI$condGetter\fP Elément de récupération de la condition 
.br
\fI$comparator\fP Comparateur 
.br
\fI$conditionValue\fP Valeur à vérifier 
.RE
.PP

.PP
Définition à la ligne \fB30\fP du fichier \fBDatabaseCondition\&.php\fP\&.
.SH "Documentation des fonctions membres"
.PP 
.SS "getComparator ()"

.PP
\fBRenvoie\fP
.RS 4
DatabaseComparator Comparateur 
.RE
.PP

.PP
Réimplémentée dans \fBMysqlCondition\fP\&.
.PP
Définition à la ligne \fB53\fP du fichier \fBDatabaseCondition\&.php\fP\&.
.SS "getCondGetter ()"

.PP
\fBRenvoie\fP
.RS 4
mixed Elément de récupération de la condition 
.RE
.PP

.PP
Réimplémentée dans \fBMysqlCondition\fP\&.
.PP
Définition à la ligne \fB39\fP du fichier \fBDatabaseCondition\&.php\fP\&.
.SS "getConditionValue ()"

.PP
\fBRenvoie\fP
.RS 4
mixed Valeur à vérifier 
.RE
.PP

.PP
Définition à la ligne \fB46\fP du fichier \fBDatabaseCondition\&.php\fP\&.
.SH "Documentation des champs"
.PP 
.SS "\fBDatabaseComparator\fP $comparator\fC [protected]\fP"

.PP
Définition à la ligne \fB23\fP du fichier \fBDatabaseCondition\&.php\fP\&.
.SS "mixed $condGetter\fC [protected]\fP"

.PP
Définition à la ligne \fB13\fP du fichier \fBDatabaseCondition\&.php\fP\&.
.SS "mixed $conditionValue\fC [protected]\fP"

.PP
Définition à la ligne \fB18\fP du fichier \fBDatabaseCondition\&.php\fP\&.

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Sabo final à partir du code source\&.
