.TH "SaboCore\Routing\Response" 3 "Mardi 23 Juillet 2024" "Version 1.1.1" "Sabo final" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SaboCore\Routing\Response
.SH SYNOPSIS
.br
.PP
.SS "Structures de données"

.in +1c
.ti -1c
.RI "class \fBBladeResponse\fP"
.br
.RI "Réponse fichier blade\&. "
.ti -1c
.RI "class \fBDownloadResponse\fP"
.br
.RI "Réponse de téléchargement\&. "
.ti -1c
.RI "class \fBHtmlResponse\fP"
.br
.RI "Réponse html\&. "
.ti -1c
.RI "class \fBJsonResponse\fP"
.br
.RI "Réponse json\&. "
.ti -1c
.RI "class \fBRedirectResponse\fP"
.br
.RI "Réponse redirection\&. "
.ti -1c
.RI "class \fBResourceResponse\fP"
.br
.RI "Réponse ressource\&. "
.ti -1c
.RI "class \fBResponse\fP"
.br
.RI "Gestionnaire de retour de réponse\&. "
.ti -1c
.RI "class \fBTwigResponse\fP"
.br
.RI "Réponse twig\&. "
.in -1c
.SS "Énumérations"

.in +1c
.ti -1c
.RI "enum \fBResponseCode\fP : int { \fBINTERNAL_SERVER_ERROR\fP = 500 }"
.br
.RI "Codes retours http\&. "
.in -1c
.SH "Documentation du type de l'énumération"
.PP 
.SS "enum \fBResponseCode\fP : int"

.PP
Codes retours http\&. 
.PP
\fBAuteur\fP
.RS 4
yahaya bathily https://github.com/yahvya 
.RE
.PP

.PP
\fBValeurs énumérées\fP
.in +1c
.TP
\fB\fIINTERNAL_SERVER_ERROR \fP\fP
Succès de la requête\&. La requête a été traitée avec succès et a entraîné la création d'une ressource\&.
.PP
La réponse est vide (pas de contenu à renvoyer)\&.
.PP
La syntaxe de la requête est erronée\&.
.PP
L'accès à la ressource est refusé en raison d'informations d'identification invalides\&.
.PP
Le serveur a compris la requête, mais refuse de la traiter\&.
.PP
La ressource demandée n'a pas été trouvée sur le serveur\&.
.PP
Erreur interne du serveur\&. 
.PP
Définition à la ligne \fB9\fP du fichier \fBResponseCode\&.php\fP\&.
.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Sabo final à partir du code source\&.
