.TH "FormFileManager" 3 "Mardi 23 Juillet 2024" "Version 1.1.1" "Sabo final" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FormFileManager \- Gestionnaire de fichier provenant de formulaire ($_FILES)  

.SH SYNOPSIS
.br
.PP
.PP
Est dérivée de \fBFileManager\fP\&.
.SS "Fonctions membres publiques"

.in +1c
.ti -1c
.RI "\fB__construct\fP (array $fileDatas)"
.br
.ti -1c
.RI "\fBgetToDownload\fP (?string $fileName=null)"
.br
.ti -1c
.RI "\fBstoreIn\fP (string $path, bool $createFoldersIfNotExists=true)"
.br
.RI "Stock le fichier dans le dossier de stockage (en conservant le fichier actuel) "
.ti -1c
.RI "\fBgetFromStorage\fP ()"
.br
.ti -1c
.RI "\fBdelete\fP ()"
.br
.ti -1c
.RI "\fBgetType\fP ()"
.br
.ti -1c
.RI "\fBisInTypes\fP (string \&.\&.\&. $typesToCheck)"
.br
.RI "Vérifie si le type mime contenu du fichier est présent dans la liste fournie\&. "
.ti -1c
.RI "\fBgetErrorState\fP ()"
.br
.ti -1c
.RI "\fBgetSize\fP ()"
.br
.in -1c

Fonctions membres publiques hérités de \fBFileManager\fP
.in +1c
.ti -1c
.RI "\fB__construct\fP (string $fileAbsolutePath)"
.br
.ti -1c
.RI "\fBfileExists\fP ()"
.br
.ti -1c
.RI "\fBgetExtension\fP (bool $fromFirstOccur=true, string $extensionSeparator='\&.')"
.br
.RI "Recherche l'extension du fichier\&. "
.ti -1c
.RI "\fBgetToDownload\fP (?string $fileName=null)"
.br
.ti -1c
.RI "\fBgetPath\fP ()"
.br
.ti -1c
.RI "\fBstoreIn\fP (string $path, bool $createFoldersIfNotExists=true)"
.br
.RI "Stock le fichier dans le dossier de stockage (en conservant le fichier actuel) "
.ti -1c
.RI "\fBdelete\fP ()"
.br
.RI "Supprime le fichier\&. "
.ti -1c
.RI "\fBgetFromStorage\fP ()"
.br
.in -1c

Fonctions membres publiques hérités de \fBStorable\fP
.in +1c
.ti -1c
.RI "\fBstoreIn\fP (string $path)"
.br
.RI "Stocke l'élément\&. "
.ti -1c
.RI "\fBgetFromStorage\fP ()"
.br
.in -1c
.SS "Attributs protégés"

.in +1c
.ti -1c
.RI "array \fB$fileDatas\fP"
.br
.in -1c

Attributs protégés hérités de \fBFileManager\fP
.in +1c
.ti -1c
.RI "string \fB$fileAbsolutePath\fP"
.br
.in -1c
.SH "Description détaillée"
.PP 
Gestionnaire de fichier provenant de formulaire ($_FILES) 


.PP
\fBAuteur\fP
.RS 4
yahaya bathily 
.RE
.PP

.PP
Définition à la ligne \fB14\fP du fichier \fBFormFileManager\&.php\fP\&.
.SH "Documentation des constructeurs et destructeur"
.PP 
.SS "__construct (array $fileDatas)"

.PP
Définition à la ligne \fB20\fP du fichier \fBFormFileManager\&.php\fP\&.
.SH "Documentation des fonctions membres"
.PP 
.SS "delete ()"
@inheritDoc 
.PP
\fBAttention\fP
.RS 4
fonction inactive pour les fichiers de formulaire, passer par FileManager 
.RE
.PP

.PP
Réimplémentée à partir de \fBFileManager\fP\&.
.PP
Définition à la ligne \fB61\fP du fichier \fBFormFileManager\&.php\fP\&.
.SS "getErrorState ()"

.PP
\fBRenvoie\fP
.RS 4
int l'état de l'erreur contenue 
.RE
.PP

.PP
Définition à la ligne \fB84\fP du fichier \fBFormFileManager\&.php\fP\&.
.SS "getFromStorage ()"
@inheritDoc 
.PP
\fBAttention\fP
.RS 4
fonction inactive pour les fichiers de formulaire, passer par FileManager 
.RE
.PP

.PP
Réimplémentée à partir de \fBFileManager\fP\&.
.PP
Définition à la ligne \fB52\fP du fichier \fBFormFileManager\&.php\fP\&.
.SS "getSize ()"

.PP
\fBRenvoie\fP
.RS 4
int la taille contenu 
.RE
.PP

.PP
Définition à la ligne \fB91\fP du fichier \fBFormFileManager\&.php\fP\&.
.SS "getToDownload (?string $fileName = \fCnull\fP)"

.PP
\fBParamètres\fP
.RS 4
\fI$fileName\fP @inheritDoc 
.RE
.PP
\fBAttention\fP
.RS 4
fonction inactive pour les fichiers de formulaire, passer par FileManager 
.RE
.PP

.PP
Réimplémentée à partir de \fBFileManager\fP\&.
.PP
Définition à la ligne \fB32\fP du fichier \fBFormFileManager\&.php\fP\&.
.SS "getType ()"

.PP
\fBRenvoie\fP
.RS 4
string le type mime contenu du fichier 
.RE
.PP

.PP
Définition à la ligne \fB68\fP du fichier \fBFormFileManager\&.php\fP\&.
.SS "isInTypes (string \&.\&.\&. $typesToCheck)"

.PP
Vérifie si le type mime contenu du fichier est présent dans la liste fournie\&. 
.PP
\fBParamètres\fP
.RS 4
\fIstring\fP \&.\&.\&.$typesToCheck 
.RE
.PP
\fBRenvoie\fP
.RS 4
bool 
.RE
.PP

.PP
Définition à la ligne \fB77\fP du fichier \fBFormFileManager\&.php\fP\&.
.SS "storeIn (string $path, bool $createFoldersIfNotExists = \fCtrue\fP)"

.PP
Stock le fichier dans le dossier de stockage (en conservant le fichier actuel) 
.PP
\fBParamètres\fP
.RS 4
\fI$path\fP Chemin à partir du dossier de stockage comme racine (/) 
.br
\fI$createFoldersIfNotExists\fP si true et que le nouveau chemin contient des dossiers inexistants, ils seront créés 
.RE
.PP
\fBRenvoie\fP
.RS 4
bool si le stockage a réussi 
.RE
.PP

.PP
Réimplémentée à partir de \fBFileManager\fP\&.
.PP
Définition à la ligne \fB37\fP du fichier \fBFormFileManager\&.php\fP\&.
.SH "Documentation des champs"
.PP 
.SS "array $fileDatas\fC [protected]\fP"

.PP
Définition à la ligne \fB18\fP du fichier \fBFormFileManager\&.php\fP\&.

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Sabo final à partir du code source\&.
