.TH "TableName" 3 "Mardi 23 Juillet 2024" "Version 1.1.1" "Sabo final" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TableName
.SH SYNOPSIS
.br
.PP
.PP
Est dérivée de \fBSqlAttribute\fP\&.
.SS "Fonctions membres publiques"

.in +1c
.ti -1c
.RI "\fB__construct\fP (string $tableName)"
.br
.ti -1c
.RI "\fBgetTableName\fP ()"
.br
.ti -1c
.RI "\fBgetCreationSql\fP ()"
.br
.in -1c
.in +1c
.ti -1c
.RI "\fBgetCreationSql\fP ()"
.br
.in -1c
.SS "Attributs protégés"

.in +1c
.ti -1c
.RI "string \fB$tableName\fP"
.br
.in -1c
.SH "Description détaillée"
.PP 
Définition à la ligne \fB9\fP du fichier \fBTableName\&.php\fP\&.
.SH "Documentation des constructeurs et destructeur"
.PP 
.SS "__construct (string $tableName)"

.PP
\fBParamètres\fP
.RS 4
\fI$tableName\fP Nom de la table 
.RE
.PP

.PP
Définition à la ligne \fB18\fP du fichier \fBTableName\&.php\fP\&.
.SH "Documentation des fonctions membres"
.PP 
.SS "getCreationSql ()"

.PP
\fBRenvoie\fP
.RS 4
string Fourni le sql de création de l'attribut 
.RE
.PP

.PP
Réimplémentée à partir de \fBSqlAttribute\fP\&.
.PP
Définition à la ligne \fB30\fP du fichier \fBTableName\&.php\fP\&.
.SS "getTableName ()"

.PP
\fBRenvoie\fP
.RS 4
string Le nom de la table 
.RE
.PP

.PP
Définition à la ligne \fB25\fP du fichier \fBTableName\&.php\fP\&.
.SH "Documentation des champs"
.PP 
.SS "string $tableName\fC [protected]\fP"

.PP
Définition à la ligne \fB13\fP du fichier \fBTableName\&.php\fP\&.

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Sabo final à partir du code source\&.
