.TH "JoinedList" 3 "Mardi 23 Juillet 2024" "Version 1.1.1" "Sabo final" \" -*- nroff -*-
.ad l
.nh
.SH NAME
JoinedList \- Lignes jointes\&.  

.SH SYNOPSIS
.br
.PP
.PP
Est dérivée de \fBSaboList\fP\&.
.SS "Fonctions membres publiques"

.in +1c
.ti -1c
.RI "\fB__construct\fP (\fBJoinedColumn\fP $descriptor, \fBMysqlModel\fP $linkedModel)"
.br
.ti -1c
.RI "\fBloadContent\fP ()"
.br
.RI "Charge les données de la jointure\&. "
.in -1c

Fonctions membres publiques hérités de \fBSaboList\fP
.in +1c
.ti -1c
.RI "\fB__construct\fP (array $datas)"
.br
.ti -1c
.RI "\fBcount\fP ()"
.br
.RI "Retourne le nombre d'éléments contenu dans la liste\&. "
.ti -1c
.RI "\fBcurrent\fP ()"
.br
.RI "Retourne l'élément actuel de la liste\&. "
.ti -1c
.RI "\fBkey\fP ()"
.br
.RI "Retourne la clé de l'élément actuel de la liste\&. "
.ti -1c
.RI "\fBnext\fP ()"
.br
.RI "Déplace le pointeur vers l'élément suivant dans la liste\&. "
.ti -1c
.RI "\fBrewind\fP ()"
.br
.RI "Remet le pointeur à la première position dans la liste\&. "
.ti -1c
.RI "\fBvalid\fP ()"
.br
.RI "Vérifie si la position actuelle est valide dans la liste\&. "
.ti -1c
.RI "\fBgetFirst\fP ()"
.br
.ti -1c
.RI "\fBgetLast\fP ()"
.br
.ti -1c
.RI "\fBsetFinder\fP (Closure $finder)"
.br
.RI "Met à jour la fonction de recherche interne\&. "
.ti -1c
.RI "\fBisEmpty\fP ()"
.br
.ti -1c
.RI "\fBgetDefaultFinder\fP ()"
.br
.RI "Défini la fonction de recherche par défaut permettant\&. "
.ti -1c
.RI "\fBfind\fP (mixed \&.\&.\&. $toFinds)"
.br
.RI "Recherche les correspondances des données fournies et crée une liste avec\&. "
.ti -1c
.RI "\fBtoArray\fP ()"
.br
.in -1c
.SS "Attributs protégés"

.in +1c
.ti -1c
.RI "\fBJoinedColumn\fP \fB$descriptor\fP"
.br
.ti -1c
.RI "\fBMysqlModel\fP \fB$linkedModel\fP"
.br
.in -1c

Attributs protégés hérités de \fBSaboList\fP
.in +1c
.ti -1c
.RI "array \fB$datas\fP"
.br
.ti -1c
.RI "int \fB$currentPos\fP"
.br
.ti -1c
.RI "Closure \fB$finder\fP"
.br
.in -1c
.SH "Description détaillée"
.PP 
Lignes jointes\&. 


.PP
\fBAuteur\fP
.RS 4
yahaya bathily https://github.com/yahvya @template ContainedType type d'éléments contenu 
.RE
.PP

.PP
Définition à la ligne \fB15\fP du fichier \fBJoinedList\&.php\fP\&.
.SH "Documentation des constructeurs et destructeur"
.PP 
.SS "__construct (\fBJoinedColumn\fP $descriptor, \fBMysqlModel\fP $linkedModel)"

.PP
\fBParamètres\fP
.RS 4
\fI$descriptor\fP Descripteur de la jointure 
.br
\fI$linkedModel\fP model lié 
.RE
.PP

.PP
Définition à la ligne \fB30\fP du fichier \fBJoinedList\&.php\fP\&.
.SH "Documentation des fonctions membres"
.PP 
.SS "loadContent ()"

.PP
Charge les données de la jointure\&. 
.PP
\fBRenvoie\fP
.RS 4
$this 
.RE
.PP
\fBExceptions\fP
.RS 4
\fIMysqlException\fP en cas d'erreur lors du chargement 
.RE
.PP

.PP
Définition à la ligne \fB42\fP du fichier \fBJoinedList\&.php\fP\&.
.SH "Documentation des champs"
.PP 
.SS "\fBJoinedColumn\fP $descriptor\fC [protected]\fP"

.PP
Définition à la ligne \fB19\fP du fichier \fBJoinedList\&.php\fP\&.
.SS "\fBMysqlModel\fP $linkedModel\fC [protected]\fP"

.PP
Définition à la ligne \fB24\fP du fichier \fBJoinedList\&.php\fP\&.

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Sabo final à partir du code source\&.
