.TH "SaboCore\Utils\Storage" 3 "Mardi 23 Juillet 2024" "Version 1.1.1" "Sabo final" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SaboCore\Utils\Storage
.SH SYNOPSIS
.br
.PP
.SS "Structures de données"

.in +1c
.ti -1c
.RI "class \fBAppStorage\fP"
.br
.RI "Gestionnaire de stockage de l'application\&. "
.ti -1c
.RI "interface \fBStorable\fP"
.br
.RI "Représente un élement pouvant être stocké "
.in -1c
.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Sabo final à partir du code source\&.
