.TH "MysqlCondSeparator" 3 "Mardi 23 Juillet 2024" "Version 1.1.1" "Sabo final" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MysqlCondSeparator \- Séparateurs mysql\&.  

.SH SYNOPSIS
.br
.PP
.PP
Est dérivée de \fBDatabaseCondSeparator\fP\&.
.SS "Fonctions membres publiques statiques"

.in +1c
.ti -1c
.RI "static \fBAND\fP ()"
.br
.ti -1c
.RI "static \fBOR\fP ()"
.br
.ti -1c
.RI "static \fBNOT\fP ()"
.br
.ti -1c
.RI "static \fBIS_NULL\fP ()"
.br
.ti -1c
.RI "static \fBIS_NOT_NULL\fP ()"
.br
.ti -1c
.RI "static \fBGROUP_START\fP ()"
.br
.ti -1c
.RI "static \fBGROUP_END\fP ()"
.br
.in -1c
.SS "Membres hérités additionnels"


Fonctions membres publiques hérités de \fBDatabaseCondSeparator\fP
.in +1c
.ti -1c
.RI "\fBgetSeparator\fP ()"
.br
.in -1c

Fonctions membres protégées hérités de \fBDatabaseCondSeparator\fP
.in +1c
.ti -1c
.RI "\fB__construct\fP (string $separator)"
.br
.in -1c

Attributs protégés hérités de \fBDatabaseCondSeparator\fP
.in +1c
.ti -1c
.RI "string \fB$separator\fP"
.br
.in -1c
.SH "Description détaillée"
.PP 
Séparateurs mysql\&. 


.PP
\fBAuteur\fP
.RS 4
yahaya bathily https://github.com/yahvya 
.RE
.PP

.PP
Définition à la ligne \fB11\fP du fichier \fBMysqlCondSeparator\&.php\fP\&.
.SH "Documentation des fonctions membres"
.PP 
.SS "static AND ()\fC [static]\fP"

.PP
\fBRenvoie\fP
.RS 4
MysqlCondSeparator Séparateur AND 
.RE
.PP

.PP
Définition à la ligne \fB15\fP du fichier \fBMysqlCondSeparator\&.php\fP\&.
.SS "static GROUP_END ()\fC [static]\fP"

.PP
\fBRenvoie\fP
.RS 4
MysqlCondSeparator Ferme un groupe de condition 
.RE
.PP

.PP
Définition à la ligne \fB57\fP du fichier \fBMysqlCondSeparator\&.php\fP\&.
.SS "static GROUP_START ()\fC [static]\fP"

.PP
\fBRenvoie\fP
.RS 4
MysqlCondSeparator Démarre un groupe de condition 
.RE
.PP

.PP
Définition à la ligne \fB50\fP du fichier \fBMysqlCondSeparator\&.php\fP\&.
.SS "static IS_NOT_NULL ()\fC [static]\fP"

.PP
\fBRenvoie\fP
.RS 4
MysqlCondSeparator Séparateur IS NOT NULL 
.RE
.PP

.PP
Définition à la ligne \fB43\fP du fichier \fBMysqlCondSeparator\&.php\fP\&.
.SS "static IS_NULL ()\fC [static]\fP"

.PP
\fBRenvoie\fP
.RS 4
MysqlCondSeparator Séparateur IS NULL 
.RE
.PP

.PP
Définition à la ligne \fB36\fP du fichier \fBMysqlCondSeparator\&.php\fP\&.
.SS "static NOT ()\fC [static]\fP"

.PP
\fBRenvoie\fP
.RS 4
MysqlCondSeparator Séparateur NOT 
.RE
.PP

.PP
Définition à la ligne \fB29\fP du fichier \fBMysqlCondSeparator\&.php\fP\&.
.SS "static OR ()\fC [static]\fP"

.PP
\fBRenvoie\fP
.RS 4
MysqlCondSeparator Séparateur OR 
.RE
.PP

.PP
Définition à la ligne \fB22\fP du fichier \fBMysqlCondSeparator\&.php\fP\&.

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Sabo final à partir du code source\&.
