.TH "JoinedColumn" 3 "Mardi 23 Juillet 2024" "Version 1.1.1" "Sabo final" \" -*- nroff -*-
.ad l
.nh
.SH NAME
JoinedColumn \- Attribut de liaison de tables\&.  

.SH SYNOPSIS
.br
.PP
.SS "Fonctions membres publiques"

.in +1c
.ti -1c
.RI "\fB__construct\fP (string $classModel, array $joinConfig, bool $loadOnGeneration=true)"
.br
.ti -1c
.RI "\fBgetClassModel\fP ()"
.br
.ti -1c
.RI "\fBgetJoinConfig\fP ()"
.br
.ti -1c
.RI "\fBgetLoadOnGeneration\fP ()"
.br
.in -1c
.SS "Attributs protégés"

.in +1c
.ti -1c
.RI "string \fB$classModel\fP"
.br
.ti -1c
.RI "array \fB$joinConfig\fP"
.br
.ti -1c
.RI "bool \fB$loadOnGeneration\fP"
.br
.in -1c
.SH "Description détaillée"
.PP 
Attribut de liaison de tables\&. 


.PP
\fBAuteur\fP
.RS 4
yahaya bathily https://github.com/yahvya 
.RE
.PP

.PP
Définition à la ligne \fB12\fP du fichier \fBJoinedColumn\&.php\fP\&.
.SH "Documentation des constructeurs et destructeur"
.PP 
.SS "__construct (string $classModel, array $joinConfig, bool $loadOnGeneration = \fCtrue\fP)"

.PP
\fBParamètres\fP
.RS 4
\fI$classModel\fP Model la class 
.br
\fI$joinConfig\fP Configuration de jointure, indicé par les valeurs de la table actuelle et ayant comme valeur l'attribut de la table lié 
.br
\fI$loadOnGeneration\fP Si les données doivent être chargées à la génération du model\&. Si false la méthode 'loadContent' devra être appellé sur la JoinedList avant utilisation 
.RE
.PP

.PP
Définition à la ligne \fB33\fP du fichier \fBJoinedColumn\&.php\fP\&.
.SH "Documentation des fonctions membres"
.PP 
.SS "getClassModel ()"

.PP
\fBRenvoie\fP
.RS 4
string Model la class 
.RE
.PP

.PP
Définition à la ligne \fB42\fP du fichier \fBJoinedColumn\&.php\fP\&.
.SS "getJoinConfig ()"

.PP
\fBRenvoie\fP
.RS 4
array Configuration de jointure, indicé par les valeurs de la table actuelle et ayant comme valeur l'attribut de la table lié 
.RE
.PP

.PP
Définition à la ligne \fB49\fP du fichier \fBJoinedColumn\&.php\fP\&.
.SS "getLoadOnGeneration ()"

.PP
\fBRenvoie\fP
.RS 4
bool Si les données doivent être chargées à la génération du model 
.RE
.PP

.PP
Définition à la ligne \fB56\fP du fichier \fBJoinedColumn\&.php\fP\&.
.SH "Documentation des champs"
.PP 
.SS "string $classModel\fC [protected]\fP"

.PP
Définition à la ligne \fB16\fP du fichier \fBJoinedColumn\&.php\fP\&.
.SS "array $joinConfig\fC [protected]\fP"

.PP
Définition à la ligne \fB21\fP du fichier \fBJoinedColumn\&.php\fP\&.
.SS "bool $loadOnGeneration\fC [protected]\fP"

.PP
Définition à la ligne \fB26\fP du fichier \fBJoinedColumn\&.php\fP\&.

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Sabo final à partir du code source\&.
