.TH "SaboApiConfig.php" 3 "Mardi 23 Juillet 2024" "Version 1.1.1" "Sabo final" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SaboApiConfig.php
.SH SYNOPSIS
.br
.PP
.SS "Espaces de nommage"

.in +1c
.ti -1c
.RI "namespace \fBSaboCore\\Utils\\Api\fP"
.br
.in -1c
.SS "Énumérations"

.in +1c
.ti -1c
.RI "enum \fBSaboApiConfig\fP : int { \fBURL\fP = 1 }"
.br
.RI "Configuration données constructeur SaboApi\&. "
.in -1c
.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Sabo final à partir du code source\&.
