.TH "DatabaseCondSeparator" 3 "Mardi 23 Juillet 2024" "Version 1.1.1" "Sabo final" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DatabaseCondSeparator \- Représentation de la séparation entre deux conditions\&.  

.SH SYNOPSIS
.br
.PP
.PP
Dérivée par \fBMysqlCondSeparator\fP\&.
.SS "Fonctions membres publiques"

.in +1c
.ti -1c
.RI "\fBgetSeparator\fP ()"
.br
.in -1c
.SS "Fonctions membres protégées"

.in +1c
.ti -1c
.RI "\fB__construct\fP (string $separator)"
.br
.in -1c
.SS "Attributs protégés"

.in +1c
.ti -1c
.RI "string \fB$separator\fP"
.br
.in -1c
.SH "Description détaillée"
.PP 
Représentation de la séparation entre deux conditions\&. 


.PP
\fBAuteur\fP
.RS 4
yahaya bathily https://github.com/yahvya 
.RE
.PP

.PP
Définition à la ligne \fB9\fP du fichier \fBDatabaseCondSeparator\&.php\fP\&.
.SH "Documentation des constructeurs et destructeur"
.PP 
.SS "__construct (string $separator)\fC [protected]\fP"

.PP
\fBParamètres\fP
.RS 4
\fI$separator\fP Séparateur 
.RE
.PP

.PP
Définition à la ligne \fB18\fP du fichier \fBDatabaseCondSeparator\&.php\fP\&.
.SH "Documentation des fonctions membres"
.PP 
.SS "getSeparator ()"

.PP
\fBRenvoie\fP
.RS 4
string Séparateur 
.RE
.PP

.PP
Définition à la ligne \fB25\fP du fichier \fBDatabaseCondSeparator\&.php\fP\&.
.SH "Documentation des champs"
.PP 
.SS "string $separator\fC [protected]\fP"

.PP
Définition à la ligne \fB13\fP du fichier \fBDatabaseCondSeparator\&.php\fP\&.

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Sabo final à partir du code source\&.
