.TH "MaintenanceController" 3 "Mardi 23 Juillet 2024" "Version 1.1.1" "Sabo final" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MaintenanceController \- gestion de la maintenance  

.SH SYNOPSIS
.br
.PP
.PP
Est dérivée de \fBController\fP\&.
.PP
Dérivée par \fBDefaultMaintenanceController\fP\&.
.SS "Fonctions membres publiques"

.in +1c
.ti -1c
.RI "\fB__construct\fP ()"
.br
.ti -1c
.RI "\fBshowMaintenancePage\fP (string $secretLink)"
.br
.RI "Affiche la page d'authentification\&. "
.ti -1c
.RI "\fBverifyLogin\fP (\fBRequest\fP $request)"
.br
.RI "Vérifie l'accès au site\&. "
.in -1c
.in +1c
.ti -1c
.RI "\fB__construct\fP ()"
.br
.in -1c
.SH "Description détaillée"
.PP 
gestion de la maintenance 


.PP
\fBAuteur\fP
.RS 4
yahaya bathily https://github.com/yahvya 
.RE
.PP

.PP
Définition à la ligne \fB13\fP du fichier \fBMaintenanceController\&.php\fP\&.
.SH "Documentation des constructeurs et destructeur"
.PP 
.SS "__construct ()"

.PP
Réimplémentée à partir de \fBController\fP\&.
.PP
Définition à la ligne \fB14\fP du fichier \fBMaintenanceController\&.php\fP\&.
.SH "Documentation des fonctions membres"
.PP 
.SS "showMaintenancePage (string $secretLink)\fC [abstract]\fP"

.PP
Affiche la page d'authentification\&. 
.PP
\fBParamètres\fP
.RS 4
\fI$secretLink\fP lien secret de maintenance 
.RE
.PP
\fBRenvoie\fP
.RS 4
Response la réponse de gestion de maintenance 
.RE
.PP
\fBExceptions\fP
.RS 4
\fIConfigException\fP 
.RE
.PP

.PP
Réimplémentée dans \fBDefaultMaintenanceController\fP\&.
.SS "verifyLogin (\fBRequest\fP $request)\fC [abstract]\fP"

.PP
Vérifie l'accès au site\&. 
.PP
\fBParamètres\fP
.RS 4
\fI$request\fP données de requête 
.RE
.PP
\fBRenvoie\fP
.RS 4
bool si l'accès est autorisé 
.RE
.PP

.PP
Réimplémentée dans \fBDefaultMaintenanceController\fP\&.

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Sabo final à partir du code source\&.
