.TH "RoutingManager" 3 "Mardi 23 Juillet 2024" "Version 1.1.1" "Sabo final" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RoutingManager \- Gestionnaire du routing de l'application\&.  

.SH SYNOPSIS
.br
.PP
.SS "Fonctions membres publiques"

.in +1c
.ti -1c
.RI "\fB__construct\fP ()"
.br
.ti -1c
.RI "\fBstart\fP ()"
.br
.RI "Lance le routing de l'application\&. "
.in -1c
.SS "Fonctions membres publiques statiques"

.in +1c
.ti -1c
.RI "static \fBnotFoundPage\fP ()"
.br
.ti -1c
.RI "static \fBmaintenancePage\fP ()"
.br
.in -1c
.SS "Fonctions membres protégées"

.in +1c
.ti -1c
.RI "\fBisAccessibleRessource\fP ()"
.br
.RI "Vérifie si le lien est celui d'une ressource autorisée à l'accès par lien\&. "
.ti -1c
.RI "\fBlaunch\fP (array|Closure $toExecute, array $matches, \fBRequest\fP $request)"
.br
.RI "lance la fonction de traitement "
.ti -1c
.RI "\fBcheckMaintenance\fP (\fBRequest\fP $request)"
.br
.RI "Vérifie la gestion de la maintenance\&. "
.ti -1c
.RI "\fBcanAccessOnMaintenance\fP (\fBRequest\fP $request)"
.br
.ti -1c
.RI "\fBauthorizeAccessOnMaintenance\fP (\fBRequest\fP $request)"
.br
.RI "Autorise l'accès durant la maintenance\&. "
.in -1c
.SS "Attributs protégés"

.in +1c
.ti -1c
.RI "string \fB$link\fP"
.br
.in -1c
.SH "Description détaillée"
.PP 
Gestionnaire du routing de l'application\&. 
.PP
Définition à la ligne \fB26\fP du fichier \fBRoutingManager\&.php\fP\&.
.SH "Documentation des constructeurs et destructeur"
.PP 
.SS "__construct ()"

.PP
Définition à la ligne \fB32\fP du fichier \fBRoutingManager\&.php\fP\&.
.SH "Documentation des fonctions membres"
.PP 
.SS "authorizeAccessOnMaintenance (\fBRequest\fP $request)\fC [protected]\fP"

.PP
Autorise l'accès durant la maintenance\&. 
.PP
\fBParamètres\fP
.RS 4
\fI$request\fP gestionnaire de requête 
.RE
.PP
\fBRenvoie\fP
.RS 4
void 
.RE
.PP

.PP
Définition à la ligne \fB190\fP du fichier \fBRoutingManager\&.php\fP\&.
.SS "canAccessOnMaintenance (\fBRequest\fP $request)\fC [protected]\fP"

.PP
\fBParamètres\fP
.RS 4
\fI$request\fP gestionnaire de requête 
.RE
.PP
\fBRenvoie\fP
.RS 4
bool si l'utilisateur a accès au site 
.RE
.PP

.PP
Définition à la ligne \fB181\fP du fichier \fBRoutingManager\&.php\fP\&.
.SS "checkMaintenance (\fBRequest\fP $request)\fC [protected]\fP"

.PP
Vérifie la gestion de la maintenance\&. 
.PP
\fBParamètres\fP
.RS 4
\fI$request\fP requête 
.RE
.PP
\fBRenvoie\fP
.RS 4
Response|null la réponse ou null si accès autorisé 
.RE
.PP
\fBExceptions\fP
.RS 4
\fIConfigException|Throwable\fP en cas d'erreur 
.RE
.PP

.PP
Définition à la ligne \fB152\fP du fichier \fBRoutingManager\&.php\fP\&.
.SS "isAccessibleRessource ()\fC [protected]\fP"

.PP
Vérifie si le lien est celui d'une ressource autorisée à l'accès par lien\&. 
.PP
\fBRenvoie\fP
.RS 4
bool si le lien est celui d'une ressource autorisée à l'accès par lien 
.RE
.PP
\fBExceptions\fP
.RS 4
\fIConfigException\fP 
.RE
.PP

.PP
Définition à la ligne \fB83\fP du fichier \fBRoutingManager\&.php\fP\&.
.SS "launch (array|Closure $toExecute, array $matches, \fBRequest\fP $request)\fC [protected]\fP"

.PP
lance la fonction de traitement 
.PP
\fBParamètres\fP
.RS 4
\fI$toExecute\fP l'action à exécuter 
.br
\fI$matches\fP les matchs dans l'URL 
.br
\fI$request\fP la requête 
.RE
.PP
\fBRenvoie\fP
.RS 4
Response la réponse fournie 
.RE
.PP
\fBExceptions\fP
.RS 4
\fIThrowable\fP en cas d'erreur 
.RE
.PP

.PP
Définition à la ligne \fB109\fP du fichier \fBRoutingManager\&.php\fP\&.
.SS "static maintenancePage ()\fC [static]\fP"

.PP
\fBRenvoie\fP
.RS 4
HtmlResponse la page de maintenance 
.RE
.PP
\fBExceptions\fP
.RS 4
\fIConfigException\fP en cas d'erreur de configuration 
.RE
.PP

.PP
Définition à la ligne \fB209\fP du fichier \fBRoutingManager\&.php\fP\&.
.SS "static notFoundPage ()\fC [static]\fP"

.PP
\fBRenvoie\fP
.RS 4
HtmlResponse la page non trouvée 
.RE
.PP
\fBExceptions\fP
.RS 4
\fIConfigException\fP en cas d'erreur de configuration 
.RE
.PP

.PP
Définition à la ligne \fB198\fP du fichier \fBRoutingManager\&.php\fP\&.
.SS "start ()"

.PP
Lance le routing de l'application\&. 
.PP
\fBRenvoie\fP
.RS 4
Response la réponse à afficher 
.RE
.PP
\fBExceptions\fP
.RS 4
\fIConfigException|Throwable\fP en cas d'erreur 
.RE
.PP

.PP
Définition à la ligne \fB41\fP du fichier \fBRoutingManager\&.php\fP\&.
.SH "Documentation des champs"
.PP 
.SS "string $link\fC [protected]\fP"

.PP
Définition à la ligne \fB30\fP du fichier \fBRoutingManager\&.php\fP\&.

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Sabo final à partir du code source\&.
