.TH "FileContentManager" 3 "Mardi 23 Juillet 2024" "Version 1.1.1" "Sabo final" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FileContentManager \- Gestionnaire de contenu de fichiers\&.  

.SH SYNOPSIS
.br
.PP
.SS "Fonctions membres publiques"

.in +1c
.ti -1c
.RI "\fB__construct\fP (string $fileContent)"
.br
.ti -1c
.RI "\fBgetContent\fP ()"
.br
.ti -1c
.RI "\fBgetJsonContent\fP ()"
.br
.in -1c
.SS "Attributs protégés"

.in +1c
.ti -1c
.RI "string \fB$fileContent\fP"
.br
.in -1c
.SH "Description détaillée"
.PP 
Gestionnaire de contenu de fichiers\&. 


.PP
\fBAuteur\fP
.RS 4
yahaya bathily https://github.com/yahvya 
.RE
.PP

.PP
Définition à la ligne \fB11\fP du fichier \fBFileContentManager\&.php\fP\&.
.SH "Documentation des constructeurs et destructeur"
.PP 
.SS "__construct (string $fileContent)"

.PP
\fBParamètres\fP
.RS 4
\fI$fileContent\fP le contenu associé 
.RE
.PP

.PP
Définition à la ligne \fB20\fP du fichier \fBFileContentManager\&.php\fP\&.
.SH "Documentation des fonctions membres"
.PP 
.SS "getContent ()"

.PP
Définition à la ligne \fB24\fP du fichier \fBFileContentManager\&.php\fP\&.
.SS "getJsonContent ()"

.PP
\fBRenvoie\fP
.RS 4
array le contenu du fichier au format json 
.RE
.PP
\fBExceptions\fP
.RS 4
\fITreatmentException\fP si le fichier n'est pas convertible, displayable non affichable 
.RE
.PP

.PP
Définition à la ligne \fB32\fP du fichier \fBFileContentManager\&.php\fP\&.
.SH "Documentation des champs"
.PP 
.SS "string $fileContent\fC [protected]\fP"

.PP
Définition à la ligne \fB15\fP du fichier \fBFileContentManager\&.php\fP\&.

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Sabo final à partir du code source\&.
