.TH "SaboCore\Routing\Application" 3 "Mardi 23 Juillet 2024" "Version 1.1.1" "Sabo final" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SaboCore\Routing\Application
.SH SYNOPSIS
.br
.PP
.SS "Structures de données"

.in +1c
.ti -1c
.RI "class \fBApplication\fP"
.br
.RI "Gestionnaire de l'application\&. "
.ti -1c
.RI "class \fBRoutingManager\fP"
.br
.RI "Gestionnaire du routing de l'application\&. "
.in -1c
.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Sabo final à partir du code source\&.
