.TH "DatabaseComparator" 3 "Mardi 23 Juillet 2024" "Version 1.1.1" "Sabo final" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DatabaseComparator \- Représentation de la fonction de comparaison\&.  

.SH SYNOPSIS
.br
.PP
.PP
Dérivée par \fBMysqlComparator\fP\&.
.SS "Fonctions membres publiques"

.in +1c
.ti -1c
.RI "\fBgetComparator\fP ()"
.br
.in -1c
.SS "Fonctions membres protégées"

.in +1c
.ti -1c
.RI "\fB__construct\fP (string $comparator)"
.br
.in -1c
.SS "Attributs protégés"

.in +1c
.ti -1c
.RI "string \fB$comparator\fP"
.br
.in -1c
.SH "Description détaillée"
.PP 
Représentation de la fonction de comparaison\&. 


.PP
\fBAuteur\fP
.RS 4
yahaya bathily https://github.com/yahvya 
.RE
.PP

.PP
Définition à la ligne \fB9\fP du fichier \fBDatabaseComparator\&.php\fP\&.
.SH "Documentation des constructeurs et destructeur"
.PP 
.SS "__construct (string $comparator)\fC [protected]\fP"

.PP
\fBParamètres\fP
.RS 4
\fI$comparator\fP Comparateur 
.RE
.PP

.PP
Définition à la ligne \fB18\fP du fichier \fBDatabaseComparator\&.php\fP\&.
.SH "Documentation des fonctions membres"
.PP 
.SS "getComparator ()"

.PP
\fBRenvoie\fP
.RS 4
string Comparateur 
.RE
.PP

.PP
Définition à la ligne \fB25\fP du fichier \fBDatabaseComparator\&.php\fP\&.
.SH "Documentation des champs"
.PP 
.SS "string $comparator\fC [protected]\fP"

.PP
Définition à la ligne \fB13\fP du fichier \fBDatabaseComparator\&.php\fP\&.

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Sabo final à partir du code source\&.
