.TH "Verifier" 3 "Mardi 23 Juillet 2024" "Version 1.1.1" "Sabo final" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Verifier \- Gestionnaire de vérification\&.  

.SH SYNOPSIS
.br
.PP
.SS "Fonctions membres publiques"

.in +1c
.ti -1c
.RI "\fB__construct\fP (Callable $verifier, Callable|null $onFailure=null, ?Callable $onSuccess=null)"
.br
.ti -1c
.RI "\fBverify\fP (array $verifierArgs)"
.br
.RI "Exécute la condition de vérification et fourni son résultat\&. "
.ti -1c
.RI "\fBexecVerification\fP (array $verifierArgs, array $onSuccessArgs=[], array $onFailureArgs=[])"
.br
.RI "Exécute le processus de vérification en exécutant les fonctions success ou failure\&. "
.in -1c
.SS "Attributs protégés"

.in +1c
.ti -1c
.RI "array Closure \fB$verifier\fP"
.br
.ti -1c
.RI "array Closure null \fB$onFailure\fP"
.br
.ti -1c
.RI "array Closure null \fB$onSuccess\fP"
.br
.in -1c
.SH "Description détaillée"
.PP 
Gestionnaire de vérification\&. 


.PP
\fBAuteur\fP
.RS 4
yahaya bathily https://github.com/yahvya 
.RE
.PP

.PP
Définition à la ligne \fB11\fP du fichier \fBVerifier\&.php\fP\&.
.SH "Documentation des constructeurs et destructeur"
.PP 
.SS "__construct (Callable $verifier, Callable|null $onFailure = \fCnull\fP, ?Callable $onSuccess = \fCnull\fP)"

.PP
\fBParamètres\fP
.RS 4
\fI$verifier\fP condition de vérification à retour booléen 
.br
\fI$onFailure\fP action à faire en cas d'échec 
.br
\fI$onSuccess\fP action à faire en cas de succès 
.RE
.PP

.PP
Définition à la ligne \fB32\fP du fichier \fBVerifier\&.php\fP\&.
.SH "Documentation des fonctions membres"
.PP 
.SS "execVerification (array $verifierArgs, array $onSuccessArgs = \fC[]\fP, array $onFailureArgs = \fC[]\fP)"

.PP
Exécute le processus de vérification en exécutant les fonctions success ou failure\&. 
.PP
\fBParamètres\fP
.RS 4
\fI$verifierArgs\fP paramètres à envoyer à la fonction de vérification 
.br
\fI$onSuccessArgs\fP arguments à envoyer à la fonction de succès 
.br
\fI$onFailureArgs\fP arguments à envoyer à la fonction d'échec 
.RE
.PP
\fBRenvoie\fP
.RS 4
array le résultat de la vérification ['success' → \&.\&.\&.] ou ['failure' → \&.\&.\&.] ou ['verifier' → \&.\&.\&.] 
.RE
.PP

.PP
Définition à la ligne \fB54\fP du fichier \fBVerifier\&.php\fP\&.
.SS "verify (array $verifierArgs)"

.PP
Exécute la condition de vérification et fourni son résultat\&. 
.PP
\fBParamètres\fP
.RS 4
\fI$verifierArgs\fP paramètres à envoyer à la fonction de vérification 
.RE
.PP
\fBRenvoie\fP
.RS 4
bool le résultat de la vérification 
.RE
.PP

.PP
Définition à la ligne \fB43\fP du fichier \fBVerifier\&.php\fP\&.
.SH "Documentation des champs"
.PP 
.SS "array Closure null $onFailure\fC [protected]\fP"

.PP
Définition à la ligne \fB20\fP du fichier \fBVerifier\&.php\fP\&.
.SS "array Closure null $onSuccess\fC [protected]\fP"

.PP
Définition à la ligne \fB25\fP du fichier \fBVerifier\&.php\fP\&.
.SS "array Closure $verifier\fC [protected]\fP"

.PP
Définition à la ligne \fB15\fP du fichier \fBVerifier\&.php\fP\&.

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Sabo final à partir du code source\&.
