.TH "Formater" 3 "Mardi 23 Juillet 2024" "Version 1.1.1" "Sabo final" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Formater \- Formateur de donnée\&.  

.SH SYNOPSIS
.br
.PP
.PP
Dérivée par \fBJsonFormatter\fP, et \fBJsonReformer\fP\&.
.SS "Fonctions membres publiques"

.in +1c
.ti -1c
.RI "\fBformat\fP (\fBMysqlModel\fP $baseModel, mixed $data)"
.br
.RI "Formate la donnée fournie\&. "
.in -1c
.SH "Description détaillée"
.PP 
Formateur de donnée\&. 


.PP
\fBAuteur\fP
.RS 4
yahaya bathily https://github.com/yahvya 
.RE
.PP

.PP
Définition à la ligne \fB11\fP du fichier \fBFormater\&.php\fP\&.
.SH "Documentation des fonctions membres"
.PP 
.SS "format (\fBMysqlModel\fP $baseModel, mixed $data)"

.PP
Formate la donnée fournie\&. 
.PP
\fBParamètres\fP
.RS 4
\fI$baseModel\fP Model de base 
.br
\fI$data\fP La donnée à formater 
.RE
.PP
\fBRenvoie\fP
.RS 4
mixed Le résultat formaté 
.RE
.PP
\fBExceptions\fP
.RS 4
\fIFormaterException\fP en cas d'erreur 
.RE
.PP

.PP
Implémenté dans \fBJsonFormatter\fP, et \fBJsonReformer\fP\&.

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Sabo final à partir du code source\&.
