.TH "SaboSse" 3 "Mardi 23 Juillet 2024" "Version 1.1.1" "Sabo final" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SaboSse \- Utilitaire d'évènement sse\&.  

.SH SYNOPSIS
.br
.PP
.SS "Fonctions membres publiques"

.in +1c
.ti -1c
.RI "\fB__construct\fP (?\fBResourceManager\fP $resourceManager=null, int $defaultSleepTimeSec=1)"
.br
.ti -1c
.RI "\fBgetResourceManager\fP ()"
.br
.ti -1c
.RI "\fBlaunch\fP (Callable $executor,?Callable $stopVerifier=null, string $stopEventName='close')"
.br
.RI "Lance l'exécution sse\&. "
.ti -1c
.RI "\fBsendEvent\fP (string $eventName, array $eventDatas,?Callable $onError=null)"
.br
.RI "Envoi un évènement au format json\&. "
.ti -1c
.RI "\fBsetSleepTimeSec\fP (int $sleepTimeSec)"
.br
.RI "Met à jour le temps de pause dans l'exécution\&. "
.ti -1c
.RI "\fBgetSleepTimeSec\fP ()"
.br
.in -1c
.SS "Fonctions membres protégées"

.in +1c
.ti -1c
.RI "\fBsetup\fP ()"
.br
.RI "Configure l'exécution pour sse\&. "
.in -1c
.SS "Attributs protégés"

.in +1c
.ti -1c
.RI "\fBResourceManager\fP \fB$resourceManager\fP"
.br
.ti -1c
.RI "int \fB$sleepTimeSec\fP"
.br
.in -1c
.SH "Description détaillée"
.PP 
Utilitaire d'évènement sse\&. 


.PP
\fBAuteur\fP
.RS 4
yahaya bathily https://github.com/yahvya.com 
.RE
.PP

.PP
Définition à la ligne \fB11\fP du fichier \fBSaboSse\&.php\fP\&.
.SH "Documentation des constructeurs et destructeur"
.PP 
.SS "__construct (?\fBResourceManager\fP $resourceManager = \fCnull\fP, int $defaultSleepTimeSec = \fC1\fP)"

.PP
\fBParamètres\fP
.RS 4
\fIResourceManager|null\fP Gestionnaire de ressource 
.br
\fI$defaultSleepTimeSec\fP temps de pause par défaut en secondes 
.RE
.PP

.PP
Définition à la ligne \fB26\fP du fichier \fBSaboSse\&.php\fP\&.
.SH "Documentation des fonctions membres"
.PP 
.SS "getResourceManager ()"

.PP
\fBRenvoie\fP
.RS 4
ResourceManager le gestionnaire de ressource 
.RE
.PP

.PP
Définition à la ligne \fB34\fP du fichier \fBSaboSse\&.php\fP\&.
.SS "getSleepTimeSec ()"

.PP
\fBRenvoie\fP
.RS 4
int le temps de pause entre chaque tour en secondes 
.RE
.PP

.PP
Définition à la ligne \fB116\fP du fichier \fBSaboSse\&.php\fP\&.
.SS "launch (Callable $executor, ?Callable $stopVerifier = \fCnull\fP, string $stopEventName = \fC'close'\fP)"

.PP
Lance l'exécution sse\&. 
.PP
\fBParamètres\fP
.RS 4
\fI$executor\fP fonction de gestions des actions à exécuter dans la boucle d'évènement, appelé à chaque tour, reçoit en argument $this 
.br
\fI$stopVerifier\fP fonction à retour booléen , si true renvoi l'évènement de fermeture et stoppe l'exécution , reçoit en argument $this 
.br
\fI$stopEventName\fP nom de l'évènement renvoyé à la fermeture par condition 
.RE
.PP
\fBRenvoie\fP
.RS 4
$this après stoppage de l'exécution par l'utilisateur ou par condition @notice Vous pouvez redéfinir la méthode setup afin d'ajouter du paramétrage supplémentaire 
.RE
.PP

.PP
Définition à la ligne \fB46\fP du fichier \fBSaboSse\&.php\fP\&.
.SS "sendEvent (string $eventName, array $eventDatas, ?Callable $onError = \fCnull\fP)"

.PP
Envoi un évènement au format json\&. 
.PP
\fBParamètres\fP
.RS 4
\fI$eventDatas\fP contenu du message 
.br
\fI$onError\fP action à faire en cas d'erreur d'envoi, reçoit en argument $this 
.RE
.PP
\fBRenvoie\fP
.RS 4
$this 
.RE
.PP

.PP
Définition à la ligne \fB75\fP du fichier \fBSaboSse\&.php\fP\&.
.SS "setSleepTimeSec (int $sleepTimeSec)"

.PP
Met à jour le temps de pause dans l'exécution\&. 
.PP
\fBParamètres\fP
.RS 4
\fI$sleepTimeSec\fP temps de pause entre chaque tour en secondes 
.RE
.PP
\fBRenvoie\fP
.RS 4
$this 
.RE
.PP

.PP
Définition à la ligne \fB107\fP du fichier \fBSaboSse\&.php\fP\&.
.SS "setup ()\fC [protected]\fP"

.PP
Configure l'exécution pour sse\&. 
.PP
\fBRenvoie\fP
.RS 4
$this 
.RE
.PP

.PP
Définition à la ligne \fB124\fP du fichier \fBSaboSse\&.php\fP\&.
.SH "Documentation des champs"
.PP 
.SS "\fBResourceManager\fP $resourceManager\fC [protected]\fP"

.PP
Définition à la ligne \fB15\fP du fichier \fBSaboSse\&.php\fP\&.
.SS "int $sleepTimeSec\fC [protected]\fP"

.PP
Définition à la ligne \fB20\fP du fichier \fBSaboSse\&.php\fP\&.

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Sabo final à partir du code source\&.
