.TH "Printer" 3 "Mardi 23 Juillet 2024" "Version 1.1.1" "Sabo final" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Printer \- Afficheur terminal\&.  

.SH SYNOPSIS
.br
.PP
.SS "Fonctions membres publiques statiques"

.in +1c
.ti -1c
.RI "static \fBprint\fP (string $toPrint, Color $textColor,?BackgroundColor $backgroundColor=null, bool $isImportant=false)"
.br
.RI "Affiche le texte fournie sans modification\&. "
.ti -1c
.RI "static \fBprintStyle\fP (string $toPrint, Composite $compositeStyle, int $countOfLineBreak=0)"
.br
.RI "Affiche le texte fournie sans modification\&. "
.in -1c
.SH "Description détaillée"
.PP 
Afficheur terminal\&. 


.PP
\fBAuteur\fP
.RS 4
yahaya bathily https://github.com/yahvya/ 
.RE
.PP

.PP
Définition à la ligne \fB15\fP du fichier \fBPrinter\&.php\fP\&.
.SH "Documentation des fonctions membres"
.PP 
.SS "static print (string $toPrint, Color $textColor, ?BackgroundColor $backgroundColor = \fCnull\fP, bool $isImportant = \fCfalse\fP)\fC [static]\fP"

.PP
Affiche le texte fournie sans modification\&. 
.PP
\fBParamètres\fP
.RS 4
\fI$toPrint\fP texte à afficher 
.br
\fI$textColor\fP couleur du texte 
.br
\fI$backgroundColor\fP couleur de fond du texte 
.br
\fI$isImportant\fP si le texte est important 
.RE
.PP
\fBRenvoie\fP
.RS 4
void 
.RE
.PP

.PP
Définition à la ligne \fB24\fP du fichier \fBPrinter\&.php\fP\&.
.SS "static printStyle (string $toPrint, Composite $compositeStyle, int $countOfLineBreak = \fC0\fP)\fC [static]\fP"

.PP
Affiche le texte fournie sans modification\&. 
.PP
\fBParamètres\fP
.RS 4
\fI$toPrint\fP texte à afficher 
.br
\fI$compositeStyle\fP style du texte 
.br
\fI$countOfLineBreak\fP nombre de sauts de ligne après 
.RE
.PP
\fBRenvoie\fP
.RS 4
void 
.RE
.PP

.PP
Définition à la ligne \fB40\fP du fichier \fBPrinter\&.php\fP\&.

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Sabo final à partir du code source\&.
