.TH "MatchResult" 3 "Mardi 23 Juillet 2024" "Version 1.1.1" "Sabo final" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MatchResult \- Résultat de match\&.  

.SH SYNOPSIS
.br
.PP
.SS "Fonctions membres publiques"

.in +1c
.ti -1c
.RI "\fB__construct\fP (bool $haveMatch, array $matchTable=[])"
.br
.ti -1c
.RI "\fBgetHaveMatch\fP ()"
.br
.ti -1c
.RI "\fBgetMatchTable\fP ()"
.br
.in -1c
.SS "Attributs protégés"

.in +1c
.ti -1c
.RI "bool \fB$match\fP"
.br
.ti -1c
.RI "array \fB$matchTable\fP"
.br
.in -1c
.SH "Description détaillée"
.PP 
Résultat de match\&. 


.PP
\fBAuteur\fP
.RS 4
yahaya bathily https://github.com/yahvya 
.RE
.PP

.PP
Définition à la ligne \fB9\fP du fichier \fBMatchResult\&.php\fP\&.
.SH "Documentation des constructeurs et destructeur"
.PP 
.SS "__construct (bool $haveMatch, array $matchTable = \fC[]\fP)"

.PP
\fBParamètres\fP
.RS 4
\fI$haveMatch\fP si le match est fait 
.br
\fI$matchTable\fP table de match 
.RE
.PP

.PP
Définition à la ligne \fB24\fP du fichier \fBMatchResult\&.php\fP\&.
.SH "Documentation des fonctions membres"
.PP 
.SS "getHaveMatch ()"

.PP
\fBRenvoie\fP
.RS 4
bool si le match est fait 
.RE
.PP

.PP
Définition à la ligne \fB32\fP du fichier \fBMatchResult\&.php\fP\&.
.SS "getMatchTable ()"

.PP
\fBRenvoie\fP
.RS 4
array table de match 
.RE
.PP

.PP
Définition à la ligne \fB39\fP du fichier \fBMatchResult\&.php\fP\&.
.SH "Documentation des champs"
.PP 
.SS "bool $match\fC [protected]\fP"

.PP
Définition à la ligne \fB13\fP du fichier \fBMatchResult\&.php\fP\&.
.SS "array $matchTable\fC [protected]\fP"

.PP
Définition à la ligne \fB18\fP du fichier \fBMatchResult\&.php\fP\&.

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Sabo final à partir du code source\&.
