.TH "TableColumn.php" 3 "Mardi 23 Juillet 2024" "Version 1.1.1" "Sabo final" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TableColumn.php
.SH SYNOPSIS
.br
.PP
.SS "Structures de données"

.in +1c
.ti -1c
.RI "class \fBTableColumn\fP"
.br
.RI "Représentation d'une colonne\&. "
.in -1c
.SS "Espaces de nommage"

.in +1c
.ti -1c
.RI "namespace \fBSaboCore\\Database\\Default\\Attributes\fP"
.br
.in -1c
.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Sabo final à partir du code source\&.
