.TH "CustomTreatment" 3 "Mardi 23 Juillet 2024" "Version 1.1.1" "Sabo final" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CustomTreatment \- Gestionnaire de traitement customisé  

.SH SYNOPSIS
.br
.PP
.PP
Est dérivée de \fBTreatment\fP\&.
.SS "Membres hérités additionnels"


Fonctions membres protégées statiques hérités de \fBTreatment\fP
.in +1c
.ti -1c
.RI "static \fBthrowException\fP (string $errorMessage, bool $isDisplayable=true)"
.br
.RI "Lèves une exception de traitement\&. "
.ti -1c
.RI "static \fBthrowModelException\fP (\fBMysqlException\fP $exception)"
.br
.RI "Lèves une exception de traitement\&. "
.in -1c
.SH "Description détaillée"
.PP 
Gestionnaire de traitement customisé 
.PP
Définition à la ligne \fB10\fP du fichier \fBCustomTreatment\&.php\fP\&.

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Sabo final à partir du code source\&.
