.TH "twig-config.php" 3 "Mardi 23 Juillet 2024" "Version 1.1.1" "Sabo final" \" -*- nroff -*-
.ad l
.nh
.SH NAME
twig-config.php
.SH SYNOPSIS
.br
.PP
.SS "Fonctions"

.in +1c
.ti -1c
.RI "\fBregisterTwigExtensions\fP ()"
.br
.RI "Aide à la création d'extension https://symfony.com/doc/3.x/templating/twig_extension.html\&. "
.in -1c
.SH "Documentation des fonctions"
.PP 
.SS "registerTwigExtensions ()"

.PP
Aide à la création d'extension https://symfony.com/doc/3.x/templating/twig_extension.html\&. 
.PP
\fBRenvoie\fP
.RS 4
string[] tableau des class d'extensions twig [CustomExtension::class] 
.RE
.PP

.PP
Définition à la ligne \fB13\fP du fichier \fBtwig\-config\&.php\fP\&.
.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Sabo final à partir du code source\&.
